=== L2jOrg/Datapack/data/xsd/charTemplate.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="classId">
					<xs:simpleType>
						<xs:restriction base="xs:nonNegativeInteger">
							<xs:minInclusive value="0" />
							<xs:maxInclusive value="211" />
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="staticData">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:nonNegativeInteger" name="baseINT"/>
							<xs:element type="xs:nonNegativeInteger" name="baseSTR"/>
							<xs:element type="xs:nonNegativeInteger" name="baseCON"/>
							<xs:element type="xs:nonNegativeInteger" name="baseMEN"/>
							<xs:element type="xs:nonNegativeInteger" name="baseDEX"/>
							<xs:element type="xs:nonNegativeInteger" name="baseWIT"/>
							<xs:element type="xs:integer" name="physicalAbnormalResist" minOccurs="0"/>
							<xs:element type="xs:integer" name="magicAbnormalResist" minOccurs="0"/>
							<xs:element name="creationPoints">
								<xs:complexType>
									<xs:sequence minOccurs="0">
										<xs:element name="node" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute type="xs:integer" name="x" use="required" />
												<xs:attribute type="xs:integer" name="y" use="required" />
												<xs:attribute type="xs:integer" name="z" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:positiveInteger" name="basePAtk"/>
							<xs:element type="xs:positiveInteger" name="baseCritRate"/>
							<xs:element type="xs:positiveInteger" name="baseMCritRate"/>
							<xs:element name="baseAtkType">
								<xs:simpleType>
									<xs:restriction base="xs:token">
										<xs:enumeration value="FIST" />
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element type="xs:positiveInteger" name="basePAtkSpd"/>
							<xs:element type="xs:positiveInteger" name="baseMAtkSpd" minOccurs="0"/>
							<xs:element name="basePDef">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:positiveInteger" name="chest"/>
										<xs:element type="xs:positiveInteger" name="legs"/>
										<xs:element type="xs:positiveInteger" name="head"/>
										<xs:element type="xs:positiveInteger" name="feet"/>
										<xs:element type="xs:positiveInteger" name="gloves"/>
										<xs:element type="xs:positiveInteger" name="underwear"/>
										<xs:element type="xs:positiveInteger" name="cloak"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:positiveInteger" name="baseMAtk"/>
							<xs:element name="baseMDef">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:positiveInteger" name="rear"/>
										<xs:element type="xs:positiveInteger" name="lear"/>
										<xs:element type="xs:positiveInteger" name="rfinger"/>
										<xs:element type="xs:positiveInteger" name="lfinger"/>
										<xs:element type="xs:positiveInteger" name="neck"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:nonNegativeInteger" name="baseCanPenetrate"/>
							<xs:element type="xs:positiveInteger" name="baseAtkRange"/>
							<xs:element name="baseDamRange">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:nonNegativeInteger" name="verticalDirection"/>
										<xs:element type="xs:nonNegativeInteger" name="horizontalDirection"/>
										<xs:element type="xs:nonNegativeInteger" name="distance"/>
										<xs:element type="xs:nonNegativeInteger" name="width"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:positiveInteger" name="baseRndDam"/>
							<xs:element name="baseMoveSpd">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:positiveInteger" name="walk"/>
										<xs:element type="xs:positiveInteger" name="run"/>
										<xs:element type="xs:positiveInteger" name="slowSwim"/>
										<xs:element type="xs:positiveInteger" name="fastSwim"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element type="xs:positiveInteger" name="baseBreath"/>
							<xs:element type="xs:positiveInteger" name="baseSafeFall"/>
							<xs:element name="collisionMale">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:decimal" name="radius"/>
										<xs:element type="xs:decimal" name="height"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="collisionFemale">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:decimal" name="radius"/>
										<xs:element type="xs:decimal" name="height"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="lvlUpgainData">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="level" maxOccurs="107">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:decimal" name="hp"/>
										<xs:element type="xs:decimal" name="mp"/>
										<xs:element type="xs:decimal" name="cp"/>
										<xs:element type="xs:decimal" name="hpRegen"/>
										<xs:element type="xs:decimal" name="mpRegen"/>
										<xs:element type="xs:decimal" name="cpRegen"/>
									</xs:sequence>
									<xs:attribute name="val" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:positiveInteger">
												<xs:minInclusive value="1"></xs:minInclusive>
												<xs:maxInclusive value="107"></xs:maxInclusive>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== L2jOrg/Datapack/data/stats/chars/baseStats/Warlock.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/charTemplate.xsd">
	<classId>14</classId>
	<staticData>
		<baseINT>41</baseINT>
		<baseSTR>22</baseSTR>
		<baseCON>27</baseCON>
		<baseMEN>39</baseMEN>
		<baseDEX>21</baseDEX>
		<baseWIT>20</baseWIT>
		<physicalAbnormalResist>10</physicalAbnormalResist>
		<magicAbnormalResist>10</magicAbnormalResist>
		<creationPoints>
			<node x="-90875" y="248162" z="-3570" />
			<node x="-90954" y="248118" z="-3570" />
			<node x="-90918" y="248070" z="-3570" />
			<node x="-90890" y="248027" z="-3570" />
		</creationPoints>
		<basePAtk>3</basePAtk>
		<baseCritRate>4</baseCritRate>
		<baseMCritRate>5</baseMCritRate>
		<baseAtkType>FIST</baseAtkType>
		<basePAtkSpd>300</basePAtkSpd>
		<baseMAtkSpd>333</baseMAtkSpd>
		<basePDef>
			<chest>15</chest>
			<legs>8</legs>
			<head>12</head>
			<feet>7</feet>
			<gloves>8</gloves>
			<underwear>3</underwear>
			<cloak>1</cloak>
		</basePDef>
		<baseMAtk>6</baseMAtk>
		<baseMDef>
			<rear>9</rear>
			<lear>9</lear>
			<rfinger>5</rfinger>
			<lfinger>5</lfinger>
			<neck>13</neck>
		</baseMDef>
		<baseCanPenetrate>0</baseCanPenetrate>
		<baseAtkRange>20</baseAtkRange>
		<baseDamRange>
			<verticalDirection>0</verticalDirection>
			<horizontalDirection>0</horizontalDirection>
			<distance>26</distance>
			<width>120</width>
		</baseDamRange>
		<baseRndDam>10</baseRndDam>
		<baseMoveSpd>
			<walk>78</walk>
			<run>124</run>
			<slowSwim>50</slowSwim>
			<fastSwim>50</fastSwim>
		</baseMoveSpd>
		<baseBreath>100</baseBreath>
		<baseSafeFall>200</baseSafeFall>
		<collisionMale>
			<radius>7.5</radius>
			<height>22.8</height>
		</collisionMale>
		<collisionFemale>
			<radius>6.5</radius>
			<height>22.5</height>
		</collisionFemale>
	</staticData>
	<lvlUpgainData>
		<level val="1">
			<hp>101.0</hp>
			<mp>40.0</mp>
			<cp>60.6</cp>
			<hpRegen>2.0</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="2">
			<hp>116.47</hp>
			<mp>47.28</mp>
			<cp>69.882</cp>
			<hpRegen>2.05</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="3">
			<hp>132.11</hp>
			<mp>54.64</mp>
			<cp>79.266</cp>
			<hpRegen>2.1</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="4">
			<hp>147.92</hp>
			<mp>62.08</mp>
			<cp>88.752</cp>
			<hpRegen>2.15</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="5">
			<hp>163.9</hp>
			<mp>69.6</mp>
			<cp>98.34</cp>
			<hpRegen>2.2</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="6">
			<hp>180.05</hp>
			<mp>77.2</mp>
			<cp>108.03</cp>
			<hpRegen>2.25</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="7">
			<hp>196.37</hp>
			<mp>84.88</mp>
			<cp>117.822</cp>
			<hpRegen>2.3</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="8">
			<hp>212.86</hp>
			<mp>92.64</mp>
			<cp>127.716</cp>
			<hpRegen>2.35</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="9">
			<hp>229.52</hp>
			<mp>100.48</mp>
			<cp>137.712</cp>
			<hpRegen>2.4</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="10">
			<hp>246.35</hp>
			<mp>108.4</mp>
			<cp>147.81</cp>
			<hpRegen>2.45</hpRegen>
			<mpRegen>0.9</mpRegen>
			<cpRegen>2.0</cpRegen>
		</level>
		<level val="11">
			<hp>263.35</hp>
			<mp>116.4</mp>
			<cp>158.01</cp>
			<hpRegen>2.5</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="12">
			<hp>280.52</hp>
			<mp>124.48</mp>
			<cp>168.312</cp>
			<hpRegen>2.6</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="13">
			<hp>297.86</hp>
			<mp>132.64</mp>
			<cp>178.716</cp>
			<hpRegen>2.7</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="14">
			<hp>315.37</hp>
			<mp>140.88</mp>
			<cp>189.222</cp>
			<hpRegen>2.8</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="15">
			<hp>333.05</hp>
			<mp>149.2</mp>
			<cp>199.83</cp>
			<hpRegen>2.9</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="16">
			<hp>350.9</hp>
			<mp>157.6</mp>
			<cp>210.54</cp>
			<hpRegen>3.0</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="17">
			<hp>368.92</hp>
			<mp>166.08</mp>
			<cp>221.352</cp>
			<hpRegen>3.1</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="18">
			<hp>387.11</hp>
			<mp>174.64</mp>
			<cp>232.266</cp>
			<hpRegen>3.2</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="19">
			<hp>405.47</hp>
			<mp>183.28</mp>
			<cp>243.282</cp>
			<hpRegen>3.3</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="20">
			<hp>424.0</hp>
			<mp>192.0</mp>
			<cp>254.4</cp>
			<hpRegen>3.4</hpRegen>
			<mpRegen>1.2</mpRegen>
			<cpRegen>2.5</cpRegen>
		</level>
		<level val="21">
			<hp>451.5</hp>
			<mp>205.2</mp>
			<cp>270.9</cp>
			<hpRegen>3.5</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="22">
			<hp>479.25</hp>
			<mp>218.52</mp>
			<cp>287.55</cp>
			<hpRegen>3.6</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="23">
			<hp>507.25</hp>
			<mp>231.96</mp>
			<cp>304.35</cp>
			<hpRegen>3.7</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="24">
			<hp>535.5</hp>
			<mp>245.52</mp>
			<cp>321.3</cp>
			<hpRegen>3.8</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="25">
			<hp>564.0</hp>
			<mp>259.2</mp>
			<cp>338.4</cp>
			<hpRegen>3.9</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="26">
			<hp>592.75</hp>
			<mp>273.0</mp>
			<cp>355.65</cp>
			<hpRegen>4.0</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="27">
			<hp>621.75</hp>
			<mp>286.92</mp>
			<cp>373.05</cp>
			<hpRegen>4.1</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="28">
			<hp>651.0</hp>
			<mp>300.96</mp>
			<cp>390.6</cp>
			<hpRegen>4.2</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="29">
			<hp>680.5</hp>
			<mp>315.12</mp>
			<cp>408.3</cp>
			<hpRegen>4.3</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="30">
			<hp>710.25</hp>
			<mp>329.4</mp>
			<cp>426.15</cp>
			<hpRegen>4.4</hpRegen>
			<mpRegen>1.5</mpRegen>
			<cpRegen>3.5</cpRegen>
		</level>
		<level val="31">
			<hp>740.25</hp>
			<mp>343.8</mp>
			<cp>444.15</cp>
			<hpRegen>4.5</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="32">
			<hp>770.5</hp>
			<mp>358.32</mp>
			<cp>462.3</cp>
			<hpRegen>4.6</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="33">
			<hp>801.0</hp>
			<mp>372.96</mp>
			<cp>480.6</cp>
			<hpRegen>4.7</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="34">
			<hp>831.75</hp>
			<mp>387.72</mp>
			<cp>499.05</cp>
			<hpRegen>4.8</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="35">
			<hp>862.75</hp>
			<mp>402.6</mp>
			<cp>517.65</cp>
			<hpRegen>4.9</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="36">
			<hp>894.0</hp>
			<mp>417.6</mp>
			<cp>536.4</cp>
			<hpRegen>5.0</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="37">
			<hp>925.5</hp>
			<mp>432.72</mp>
			<cp>555.3</cp>
			<hpRegen>5.1</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="38">
			<hp>957.25</hp>
			<mp>447.96</mp>
			<cp>574.35</cp>
			<hpRegen>5.2</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="39">
			<hp>989.25</hp>
			<mp>463.32</mp>
			<cp>593.55</cp>
			<hpRegen>5.3</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="40">
			<hp>1021.5</hp>
			<mp>478.8</mp>
			<cp>612.9</cp>
			<hpRegen>5.4</hpRegen>
			<mpRegen>1.8</mpRegen>
			<cpRegen>4.5</cpRegen>
		</level>
		<level val="41">
			<hp>1070.9</hp>
			<mp>504.8</mp>
			<cp>642.54</cp>
			<hpRegen>5.5</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="42">
			<hp>1120.68</hp>
			<mp>531.0</mp>
			<cp>672.408</cp>
			<hpRegen>5.6</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="43">
			<hp>1170.84</hp>
			<mp>557.4</mp>
			<cp>702.504</cp>
			<hpRegen>5.7</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="44">
			<hp>1221.38</hp>
			<mp>584.0</mp>
			<cp>732.828</cp>
			<hpRegen>5.8</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="45">
			<hp>1272.3</hp>
			<mp>610.8</mp>
			<cp>763.38</cp>
			<hpRegen>5.9</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="46">
			<hp>1323.6</hp>
			<mp>637.8</mp>
			<cp>794.16</cp>
			<hpRegen>6.0</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="47">
			<hp>1375.28</hp>
			<mp>665.0</mp>
			<cp>825.168</cp>
			<hpRegen>6.1</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="48">
			<hp>1427.34</hp>
			<mp>692.4</mp>
			<cp>856.404</cp>
			<hpRegen>6.2</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="49">
			<hp>1479.78</hp>
			<mp>720.0</mp>
			<cp>887.868</cp>
			<hpRegen>6.3</hpRegen>
			<mpRegen>2.1</mpRegen>
			<cpRegen>5.5</cpRegen>
		</level>
		<level val="50">
			<hp>1532.6</hp>
			<mp>747.8</mp>
			<cp>919.56</cp>
