=== L2jOrg/Datapack/data/xsd/skillTrees.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://l2j.org"
		   xmlns="http://l2j.org"
		   elementFormDefault="qualified">

	<xs:include schemaLocation="common.xsd"/>

	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="skillTree" type="SkillTreeType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="SkillTreeType">
		<xs:sequence>
			<xs:element name="skill" type="LearnSkillType" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="classId" type="ClassId"/>
		<xs:attribute name="parentClassId" type="ClassId"/>
		<xs:attribute name="type" type="TreeType" use="required"/>
		<xs:attribute name="race" type="Race"/>
	</xs:complexType>

	<xs:complexType name="LearnSkillType">
		<xs:sequence>
			<xs:element name="social-status" type="SocialStatus" minOccurs="0"/>
			<xs:element name="residenceId" type="xs:positiveInteger" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="race" type="Race" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="replace-skill" type="SkillInfo" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="item"  type="ItemInfo" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="autoGet" type="xs:boolean" default="false"/>  
		<xs:attribute name="required-level" type="xs:positiveInteger"/>
		<xs:attribute name="learnedByNpc" type="xs:boolean" />
		<xs:attribute name="levelUpSp" type="xs:long" />
		<xs:attribute name="skillId" type="xs:positiveInteger" use="required" />
		<xs:attribute name="skillLvl" type="xs:positiveInteger" use="required" />
		<xs:attribute name="skillName" type="xs:normalizedString" use="required" />
	</xs:complexType>

	<xs:simpleType name="TreeType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="abilitySkillTree" />
			<xs:enumeration value="alchemySkillTree" />
			<xs:enumeration value="classSkillTree" />
			<xs:enumeration value="collectSkillTree" />
			<xs:enumeration value="fishingSkillTree" />
			<xs:enumeration value="gameMasterSkillTree" />
			<xs:enumeration value="heroSkillTree" />
			<xs:enumeration value="pledgeSkillTree" />
			<xs:enumeration value="raceSkillTree" />
			<xs:enumeration value="transferSkillTree" />
			<xs:enumeration value="transformSkillTree" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== L2jOrg/Datapack/data/skillTrees/1stClass/HumanKnight.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org ../../xsd/skillTrees.xsd">
	<skillTree type="classSkillTree" classId="4" parentClassId="0">
		<skill name="Ultimate Defense" id="110" level="1" required-level="20" sp="1000" />
		<skill name="Majesty" id="82" level="1" required-level="20" sp="1000" />
		<skill name="Sword/Blunt Weapon Mastery" id="217" level="1" required-level="20" sp="1000" />
		<skill name="Heavy Armor Mastery" id="232" level="1" required-level="20" sp="1000" />
		<skill name="Heavy Armor Mastery" id="232" level="2" required-level="20" sp="1000" />
		<skill name="Heavy Armor Mastery" id="232" level="3" required-level="20" sp="1000" />
		<skill name="Shield Mastery" id="153" level="1" required-level="20" sp="1000" />
		<skill name="Magic Resistance" id="147" level="1" required-level="20" sp="1000" />
		<skill name="Magic Resistance" id="147" level="2" required-level="20" sp="1000" />
		<skill name="Shield Stun" id="92" level="1" required-level="20" sp="1000" />
		<skill name="Shield Stun" id="92" level="2" required-level="20" sp="1000" />
		<skill name="Shield Stun" id="92" level="3" required-level="20" sp="1000" />
		<skill name="Drain Energy" id="70" level="1" required-level="20" sp="1000">
			<item id="1097"/>
		</skill>

		<skill name="Aggression" id="28" level="1" required-level="22" sp="2800" />
		<skill name="Heavy Armor Mastery" id="232" level="4" required-level="22" sp="2800" />
		<skill name="Drain Energy" id="70" level="2" required-level="22" sp="2800" />
		<skill name="Magic Resistance" id="147" level="3" required-level="22" sp="2800" />
		<skill name="Shield Stun" id="92" level="4" required-level="22" sp="2800" />

		<skill name="Aggression" id="28" level="2" required-level="23" sp="2800" />
		<skill name="Heavy Armor Mastery" id="232" level="5" required-level="23" sp="2800" />
		<skill name="Drain Energy" id="70" level="3" required-level="23" sp="2800" />
		<skill name="Magic Resistance" id="147" level="4" required-level="23" sp="2800" />
		<skill name="Shield Stun" id="92" level="5" required-level="23" sp="2800" />
		
		<skill name="Aggression" id="28" level="3" required-level="24" sp="2800" />
		<skill name="Sword/Blunt Weapon Mastery" id="217" level="2" required-level="24" sp="2800" />
		<skill name="Heavy Armor Mastery" id="232" level="6" required-level="24" sp="2800" />
		<skill name="Drain Energy" id="70" level="4" required-level="24" sp="2800" />
		<skill name="Magic Resistance" id="147" level="5" required-level="24" sp="2800" />
		<skill name="Shield Stun" id="92" level="6" required-level="24" sp="2800" />
		<skill name="Deflect Arrow" id="112" level="1" required-level="24" sp="2800" />
		
		<skill name="Aggression" id="28" level="4" required-level="26" sp="5700" />
		<skill name="Sword/Blunt Weapon Mastery" id="217" level="3" required-level="26" sp="5700" />
		<skill name="Heavy Armor Mastery" id="232" level="7" required-level="26" sp="5700" />
		<skill name="Drain Energy" id="70" level="5" required-level="26" sp="5700" />
		<skill name="Magic Resistance" id="147" level="6" required-level="26" sp="5700" />
		<skill name="Shield Stun" id="92" level="7" required-level="26" sp="5700" />
		<skill name="Divine Heal" id="45" level="1" required-level="26" sp="5700">
			<item id="1378"/>
		</skill>
		
		<skill name="Aggression" id="28" level="5" required-level="27" sp="5700" />
		<skill name="Heavy Armor Mastery" id="232" level="8" required-level="27" sp="5700" />
		<skill name="Drain Energy" id="70" level="6" required-level="27" sp="5700" />
		<skill name="Magic Resistance" id="147" level="7" required-level="27" sp="5700" />
		<skill name="Shield Stun" id="92" level="8" required-level="27" sp="5700" />
		<skill name="Divine Heal" id="45" level="2" required-level="27" sp="5700" />
		
		<skill name="Aggression" id="28" level="6" required-level="28" sp="5700" />
		<skill name="Sword/Blunt Weapon Mastery" id="217" level="4" required-level="28" sp="5700" />
		<skill name="Heavy Armor Mastery" id="232" level="9" required-level="28" sp="5700" />
		<skill name="Shield Mastery" id="153" level="2" required-level="28" sp="5700" />
		<skill name="Drain Energy" id="70" level="7" required-level="28" sp="5700" />
		<skill name="Magic Resistance" id="147" level="8" required-level="28" sp="5700" />
		<skill name="Shield Stun" id="92" level="9" required-level="28" sp="5700" />
		<skill name="Divine Heal" id="45" level="3" required-level="28" sp="5700" />
		
		<skill name="Aggression" id="28" level="7" required-level="30" sp="11000" />
		<skill name="Sword/Blunt Weapon Mastery" id="217" level="5" required-level="30" sp="11000" />
		<skill name="Heavy Armor Mastery" id="232" level="10" required-level="30" sp="11000" />
		<skill name="Drain Energy" id="70" level="8" required-level="30" sp="11000" />
		<skill name="Magic Resistance" id="147" level="9" required-level="30" sp="11000" />
		<skill name="Shield Stun" id="92" level="10" required-level="30" sp="11000" />
		<skill name="Divine Heal" id="45" level="4" required-level="30" sp="11000" />
		
		<skill name="Aggression" id="28" level="8" required-level="31" sp="11000" />
		<skill name="Heavy Armor Mastery" id="232" level="11" required-level="31" sp="11000" />
		<skill name="Drain Energy" id="70" level="9" required-level="31" sp="11000" />
		<skill name="Magic Resistance" id="147" level="10" required-level="31" sp="11000" />
		<skill name="Shield Stun" id="92" level="11" required-level="31" sp="11000" />
		<skill name="Divine Heal" id="45" level="5" required-level="31" sp="11000" />
		
		<skill name="Aggression" id="28" level="9" required-level="32" sp="11000" />
		<skill name="Sword/Blunt Weapon Mastery" id="217" level="6" required-level="32" sp="11000" />
		<skill name="Heavy Armor Mastery" id="232" level="12" required-level="32" sp="11000" />
		<skill name="Drain Energy" id="70" level="10" required-level="32" sp="11000" />
		<skill name="Magic Resistance" id="147" level="11" required-level="32" sp="11000" />
		<skill name="Shield Stun" id="92" level="12" required-level="32" sp="11000" />
		<skill name="Deflect Arrow" id="112" level="2" required-level="32" sp="11000" />
		<skill name="Divine Heal" id="45" level="6" required-level="32" sp="11000" />

		<skill name="Aggression" id="28" level="10" required-level="34" sp="20000" />
		<skill name="Sword/Blunt Weapon Mastery" id="217" level="7" required-level="34" sp="20000" />
		<skill name="Heavy Armor Mastery" id="232" level="13" required-level="34" sp="20000" />
		<skill name="Drain Energy" id="70" level="11" required-level="34" sp="20000" />
		<skill name="Magic Resistance" id="147" level="12" required-level="34" sp="20000" />
		<skill name="Shield Stun" id="92" level="13" required-level="34" sp="20000" />
		<skill name="Divine Heal" id="45" level="7" required-level="34" sp="20000" />
		
		<skill name="Aggression" id="28" level="11" required-level="35" sp="20000" />
		<skill name="Heavy Armor Mastery" id="232" level="14" required-level="35" sp="20000" />
		<skill name="Drain Energy" id="70" level="12" required-level="35" sp="20000" />
		<skill name="Magic Resistance" id="147" level="13" required-level="35" sp="20000" />
		<skill name="Shield Stun" id="92" level="14" required-level="35" sp="20000" />
		<skill name="Divine Heal" id="45" level="8" required-level="35" sp="20000" />
		
		<skill name="Aggression" id="28" level="12" required-level="36" sp="20000" />
		<skill name="Sword/Blunt Weapon Mastery" id="217" level="8" required-level="36" sp="20000" />
		<skill name="Heavy Armor Mastery" id="232" level="15" required-level="36" sp="20000" />
		<skill name="Drain Energy" id="70" level="13" required-level="36" sp="20000" />
		<skill name="Magic Resistance" id="147" level="14" required-level="36" sp="20000" />
		<skill name="Shield Stun" id="92" level="15" required-level="36" sp="20000" />
		<skill name="Divine Heal" id="45" level="9" required-level="36" sp="20000" />
		<skill name="Focus Mind" id="191" level="1" required-level="36" sp="20000" />
	</skillTree>
</list>

=== L2jOrg/Datapack/data/skillTrees/1stClass/SylphGunner.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org ../../xsd/skillTrees.xsd">
	<skillTree type="classSkillTree" classId="209" parentClassId="208">

		<!-- Master Buffs Lv. 20 -->
		<skill name="Elemental Empower" id="47029" level="1" required-level="20" sp="1000" />
		<skill name="Elemental Wind Walk" id="47024" level="1" required-level="20" sp="1000" />
		<skill name="Elemental Might" id="47026" level="2" required-level="20" sp="1000" />
		<skill name="Elemental Acumen" id="47028" level="1" required-level="20" sp="1000" />
		<skill name="Elemental Haste" id="47023" level="1" required-level="20" sp="1000" />
		<skill name="Elemental Focus" id="47021" level="1" required-level="20" sp="1000" />
		<skill name="Elemental Clarity" id="47032" level="1" required-level="20" sp="1000" />
		<skill name="Elemental Death Whisper" id="47022" level="1" required-level="20" sp="1000" />
		<skill name="Elemental Shield" id="47027" level="2" required-level="20" sp="1000" />

		<!-- Skills Lv20 -->
		<skill name="Light Armor Mastery" id="47082" level="1" required-level="20" sp="1000" />
		<skill name="Firearms Mastery" id="47081" level="1" required-level="20" sp="1000" />
		<skill name="Recover HP" id="45176" level="1" required-level="20" sp="1000" />
		<skill name="Recover MP" id="45177" level="1" required-level="20" sp="1000" />
		<skill name="Ability to Protect" id="91" level="2" required-level="20" sp="1000" />
		<skill name="Soul Strike" id="1516" level="1" required-level="20" sp="1000" />
		<skill name="Dual Blow" id="47002" level="1" required-level="20" sp="1000" />
		<skill name="Elemental Connection" id="47104" level="2" required-level="40" sp="1000" />

		<!-- Skills Lv21 -->
		<skill name="Dual Blow" id="47002" level="2" required-level="21" sp="2500" />

		<!-- Skills Lv25 -->
		<skill name="Ability to Attack" id="77" level="2" required-level="25" sp="5500" />

		<!-- Skills Lv27 -->
		<skill name="Critical Chance" id="137" level="1" required-level="27" sp="5500" />

		<!-- Skills Lv28 -->
		<skill name="Dual Blow" id="47002" level="3" required-level="28" sp="5500" />


		<!-- Skills Lv30 -->
		<skill name="Elemental Focus" id="47021" level="1" required-level="2" sp="10000" />
		<skill name="Elemental Death Whisper" id="47022" level="2" required-level="20" sp="10000" />
		<skill name="Elemental Wind Walk" id="47024" level="2" required-level="20" sp="1000" />
		<skill name="Elemental Magic Barrier" id="47025" level="1" required-level="20" sp="10000" />
		<skill name="Elemental Acumen" id="47028" level="2" required-level="20" sp="10000" />
		<skill name="Elemental Empower" id="47029" level="2" required-level="20" sp="10000" />
		<skill name="Elemental Wild Magic" id="47030" level="1" required-level="20" sp="10000" />
		<skill name="Elemental Berserker Spirit" id="47031" level="1" required-level="30" sp="10000" />
		<skill name="Elemental Clarity" id="47032" level="2" required-level="30" sp="10000" />

		<!-- Skills Lv32 -->
		<skill name="Dual Blow" id="47002" level="4" required-level="32" sp="18000" />

		<!-- Skills Lv35 -->
		<skill name="Long Range Attack" id="47084" level="1" required-level="35" sp="20000" />

		<!-- Skills Lv36 -->
		<skill name="Dual Blow" id="47002" level="5" required-level="36" sp="20000" />
		
	</skillTree>
</list>

=== L2jOrg/Datapack/data/skillTrees/2ndClass/SylphFreeHunter.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org ../../xsd/skillTrees.xsd">
	<skillTree type="classSkillTree" classId="210" parentClassId="209">
	
		<!-- Skills Lv40 -->		
		<skill name="Weapon Mastery" id="141" level="4" required-level="40" sp="100000"/>
		<skill name="Armor Mastery" id="142" level="4" required-level="40" sp="100000"/>
		<skill name="Dual Blow" id="47002" level="6" required-level="40" sp="100000" />
		<skill name="Freezing Wound" id="47011" level="1" required-level="40" sp="100000" />
		<skill name="Elemental Focus" id="47021" level="3" required-level="40" sp="80000" />
		<skill name="Elemental Death Whisper" id="47022" level="3" required-level="40" sp="80000" />
		<skill name="Elemental Haste" id="47023" level="2" required-level="40" sp="80000" />
		<skill name="Elemental Magic Barrier" id="47025" level="2" required-level="40" sp="80000" />
		<skill name="Elemental Might" id="47026" level="3" required-level="40" sp="80000" />
		<skill name="Elemental Shield" id="47027" level="3" required-level="40" sp="80000" />
		<skill name="Elemental Acumen" id="47028" level="3" required-level="40" sp="80000" />
		<skill name="Elemental Empower" id="47029" level="3" required-level="40" sp="80000" />
		<skill name="Elemental Wild Magic" id="47030" level="2" required-level="40" sp="80000" />
		<skill name="Elemental Berserker Spirit" id="47031" level="2" required-level="40" sp="80000" />
		<skill name="Elemental Clarity" id="47032" level="3" required-level="40" sp="80000" />
		<skill name="Elemental Wind" id="47061" level="1" required-level="40" sp="100000" />
		<skill name="Time Burst" id="47062" level="1" required-level="40" sp="100000" />
		<skill name="Firearms Mastery" id="47081" level="2" required-level="40" sp="100000" />
		<skill name="Light Armor Mastery" id="47082" level="2" required-level="40" sp="10000" />
		<skill name="Elemental Spirit" id="47101" level="2" required-level="40" sp="100000" />
		<skill name="Elemental Connection" id="47104" level="3" required-level="40" sp="100000" />
		<skill name="Elemental Recovery" id="47105" level="1" required-level="40" sp="100000" />
		<skill name="Recover HP" id="45176" level="1" required-level="20" sp="1000" />
		<skill name="Recover MP" id="45177" level="1" required-level="20" sp="1000" />
		<skill name="Elemental Wind Walk" id="47024" level="1" required-level="20" sp="1000" />
		<skill name="Ability to Protect" id="91" level="2" required-level="20" sp="1000" />
		<skill name="Soul Strike" id="1516" level="1" required-level="20" sp="1000" />
		<skill name="Elemental Clarity" id="47032" level="1" required-level="20" sp="1000" />
		<skill name="Dual Blow" id="47002" level="1" required-level="20" sp="1000" />

		<!-- Skills Lv41 -->		
		<skill name="Boost Evasion" id="198" level="1" required-level="41" sp="110000" />

		<!-- Skills Lv42 -->		
		<skill name="Quick Step" id="169" level="1" required-level="42" sp="120000" />

		<!-- Skills Lv43 -->		
		<skill name="Dual Blow" id="47002" level="7" required-level="43" sp="130000" />

		<!-- Skills Lv44 -->		
		<skill name="Quick Recharge" id="47083" level="1" required-level="44" sp="140000" />

		<!-- Skills Lv45 -->
		<skill name="Critical Chance" id="137" level="2" required-level="45" sp="150000" />
		<skill name="Pirate Transformation" id="1800" level="1" required-level="45" auto-learn="true" />
		
		<!-- Skills Lv46 -->		
		<skill name="Dual Blow" id="47002" level="8" required-level="46" sp="160000" />
		
		<!-- Skills Lv47 -->		
		<skill name="Light Armor Mastery" id="47082" level="3" required-level="47" sp="170000" />
		
		<!-- Skills Lv48 -->		
		<skill name="Firearms Mastery" id="47081" level="3" required-level="48" sp="180000" />

		<!-- Skills Lv49 -->		
		<skill name="Dual Blow" id="47002" level="9" required-level="49" sp="200000" />
		
		<!-- Skills Lv50 -->		
		<skill name="Quick Step" id="169" level="2" required-level="50" sp="220000" />
		<skill name="Recover HP" id="45176" level="2" required-level="50" sp="300000" />
		<skill name="Recover MP" id="45177" level="2" required-level="50" sp="300000" />
		<skill name="Freezing Wound" id="47011" level="2" required-level="50" sp="220000" />

		<!-- Skills Lv52 -->
		<skill name="Divine Inspiration" id="1405" level="1" required-level="52" sp="300000" />
		<skill name="Ability to Attack" id="77" level="2" required-level="25" sp="5500" />
		<skill name="Dual Blow" id="47002" level="10" required-level="52" sp="300000" />
		<skill name="Elemental Recovery" id="47105" level="2" required-level="52" sp="300000" />

		<!-- Skills Lv53 -->
		<skill name="Light Armor Mastery" id="47082" level="4" required-level="53" sp="400000" />

		<!-- Skills Lv54 -->		
		<skill name="Firearms Mastery" id="47081" level="4" required-level="54" sp="400000" />

		<!-- Skills Lv55 -->		
		<skill name="Boost Evasion" id="198" level="2" required-level="55" sp="450000" />
		<skill name="Dual Blow" id="47002" level="11" required-level="55" sp="450000" />
		<skill name="Long Range Attack" id="47084" level="2" required-level="55" sp="450000" />
		
		<!-- Skills Lv58 -->
		<skill name="Dual Blow" id="47002" level="12" required-level="58" sp="600000" />
		<skill name="Elemental Care" id="47054" level="1" required-level="58" sp="600000" />
		<skill name="Quick Recharge" id="47083" level="2" required-level="58" sp="600000" />
		
		<!-- Skills Lv59 -->
		<skill name="Light Armor Mastery" id="47082" level="5" required-level="59" sp="700000" />
		
		<!-- Skills Lv60 -->
		<skill name="Firearms Mastery" id="47081" level="5" required-level="60" sp="800000" />
		<skill name="Assasin Transformation" id="1801" level="1" required-level="60" auto-learn="true" />
			
		<!-- Skills Lv61 -->
		<skill name="Divine Inspiration" id="1405" level="2" required-level="61" sp="900000" />
		<skill name="Dual Blow" id="47002" level="13" required-level="61" sp="900000" />

		<!-- Skills Lv62 -->
		<skill name="Freezing Wound" id="47011" level="3" required-level="62" sp="1000000" />

		<!-- Skills Lv63 -->
		<skill name="Dual Blow" id="47002" level="14" required-level="63" sp="1100000" />

		<!-- Skills Lv64 -->
		<skill name="Elemental Recovery" id="47105" level="3" required-level="64" sp="1200000" />

		<!-- Skills Lv65 -->
		<skill name="Dual Blow" id="47002" level="15" required-level="65" sp="1300000" />
		<skill name="Light Armor Mastery" id="47082" level="6" required-level="65" sp="1300000" />

		<!-- Skills Lv66 -->		
		<skill name="Firearms Mastery" id="47081" level="6" required-level="66" sp="1400000" />
		
		<!-- Skills Lv67 -->		
		<skill name="Dual Blow" id="47002" level="16" required-level="67" sp="1500000" />
		
		<!-- Skills Lv68 -->		
		<skill name="Quick Recharge" id="47083" level="3" required-level="68" sp="1600000" />

		<!-- Skills Lv69 -->		
		<skill name="Dual Blow" id="47002" level="17" required-level="69" sp="1700000" />
		
		<!-- Skills Lv70 -->		
		<skill name="Light Assasin Transformation" id="1802" level="1" required-level="70" auto-learn="true" />
		<skill name="Elemental Recovery" id="47105" level="4" required-level="70" sp="1800000" />
				
		<!-- Skills Lv71 -->		
		<skill name="Dual Blow" id="47002" level="18" required-level="71" sp="1900000" />
		<skill name="Light Armor Mastery" id="47082" level="7" required-level="71" sp="1900000" />
				
		<!-- Skills Lv72 -->		
		<skill name="Firearms Mastery" id="47081" level="7" required-level="72" sp="2000000" />
		
		<!-- Skills Lv73 -->		
		<skill name="Dual Blow" id="47002" level="19" required-level="73" sp="2100000" />

		<!-- Skills Lv74 -->
		<skill name="Freezing Wound" id="47011" level="4" required-level="74" sp="2200000" />

		<!-- Skills Lv75 -->
		<skill name="Dual Blow" id="47002" level="20" required-level="75" sp="2300000" />
		
	</skillTree>
</list>
