=== L2jOrg/Datapack/data/xsd/skillTrees.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://l2j.org"
		   xmlns="http://l2j.org"
		   elementFormDefault="qualified">

	<xs:include schemaLocation="common.xsd"/>

	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="skillTree" type="SkillTreeType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="SkillTreeType">
		<xs:sequence>
			<xs:element name="skill" type="LearnSkillType" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="classId" type="ClassId"/>
		<xs:attribute name="parentClassId" type="ClassId"/>
		<xs:attribute name="type" type="TreeType" use="required"/>
		<xs:attribute name="race" type="Race"/>
	</xs:complexType>

	<xs:complexType name="LearnSkillType">
		<xs:sequence>
			<xs:element name="social-status" type="SocialStatus" minOccurs="0"/>
			<xs:element name="residenceId" type="xs:positiveInteger" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="race" type="Race" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="replace-skill" type="SkillInfo" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="item"  type="ItemInfo" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="autoGet" type="xs:boolean" default="false"/>  
		<xs:attribute name="required-level" type="xs:positiveInteger"/>
		<xs:attribute name="learnedByNpc" type="xs:boolean" />
		<xs:attribute name="levelUpSp" type="xs:long" />
		<xs:attribute name="skillId" type="xs:positiveInteger" use="required" />
		<xs:attribute name="skillLvl" type="xs:positiveInteger" use="required" />
		<xs:attribute name="skillName" type="xs:normalizedString" use="required" />
	</xs:complexType>

	<xs:simpleType name="TreeType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="abilitySkillTree" />
			<xs:enumeration value="alchemySkillTree" />
			<xs:enumeration value="classSkillTree" />
			<xs:enumeration value="collectSkillTree" />
			<xs:enumeration value="fishingSkillTree" />
			<xs:enumeration value="gameMasterSkillTree" />
			<xs:enumeration value="heroSkillTree" />
			<xs:enumeration value="pledgeSkillTree" />
			<xs:enumeration value="raceSkillTree" />
			<xs:enumeration value="transferSkillTree" />
			<xs:enumeration value="transformSkillTree" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== L2jOrg/Datapack/data/skillTrees/1stClass/DarkDeathBlade.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org ../../xsd/skillTrees.xsd">
	<skillTree type="classSkillTree" classId="205" parentClassId="204">

		<!-- Skills Lv20 -->
		<skill skillName="Death Armor Mastery" skillId="45354" skillLvl="4" getLevel="20" levelUpSp="1000" />
		<skill skillName="Death Sword Mastery" skillId="45353" skillLvl="4" getLevel="20" levelUpSp="1000" />
		<skill skillName="Empower" skillId="45105" skillLvl="1" getLevel="20" levelUpSp="1000" />
		<skill skillName="Recover HP" skillId="45176" skillLvl="1" getLevel="20" levelUpSp="1000" />
		<skill skillName="Recover MP" skillId="45177" skillLvl="1" getLevel="20" levelUpSp="1000" />
		<skill skillName="Punishment" skillId="45301" skillLvl="1" getLevel="20" autoGet="true" />
		<skill skillName="Wind Walk" skillId="45107" skillLvl="1" getLevel="20" levelUpSp="1000" />
		<skill skillName="Enhanced Weapon" skillId="255" skillLvl="1" getLevel="20" levelUpSp="1000" />
		<skill skillName="Enhanced Weapon" skillId="255" skillLvl="2" getLevel="20" levelUpSp="1000" />
		<skill skillName="Enhanced Weapon" skillId="255" skillLvl="3" getLevel="20" levelUpSp="1000" />
		<skill skillName="Enhanced Weapon" skillId="255" skillLvl="4" getLevel="20" levelUpSp="1000" />
		<skill skillName="Enhanced Weapon" skillId="255" skillLvl="5" getLevel="20" levelUpSp="1000" />
		<skill skillName="Might" skillId="1068" skillLvl="2" getLevel="20" levelUpSp="1000" />
		<skill skillName="Acumen" skillId="45104" skillLvl="1" getLevel="20" levelUpSp="1000" />
		<skill skillName="Ability to Protect" skillId="91" skillLvl="2" getLevel="20" levelUpSp="1000" />
		<skill skillName="Haste" skillId="45111" skillLvl="1" getLevel="20" levelUpSp="1000" />
		<skill skillName="Focus" skillId="45109" skillLvl="1" getLevel="20" levelUpSp="1000" />
		<skill skillName="Clarity" skillId="45113" skillLvl="1" getLevel="20" levelUpSp="1000" />
		<skill skillName="Death Whisper" skillId="45110" skillLvl="1" getLevel="20" levelUpSp="1000" />
		<skill skillName="Shield" skillId="1040" skillLvl="2" getLevel="20" levelUpSp="1000" />
		<skill skillName="Emergency Rescue" skillId="70" skillLvl="3" getLevel="20" levelUpSp="1000" />
		<skill skillName="Dark Elven Spirit" skillId="129" skillLvl="1" getLevel="20" levelUpSp="1000" />

		<!-- Skills Lv21 -->
		<skill skillName="Enhanced Weapon" skillId="255" skillLvl="6" getLevel="21" levelUpSp="2500" />

		<!-- Skills Lv22 -->
		<skill skillName="Enhanced Weapon" skillId="255" skillLvl="7" getLevel="22" levelUpSp="2500" />

		<!-- Skills Lv23 -->
		<skill skillName="Enhanced Weapon" skillId="255" skillLvl="8" getLevel="23" levelUpSp="2500" />

		<!-- Skills Lv24 -->
		<skill skillName="Confusion" skillId="2" skillLvl="1" getLevel="24" levelUpSp="2500" />
		<skill skillName="Confusion" skillId="2" skillLvl="2" getLevel="24" levelUpSp="2500" />
		<skill skillName="Enhanced Weapon" skillId="255" skillLvl="9" getLevel="24" levelUpSp="2500" />

		<!-- Skills Lv25 -->
		<skill skillName="Confusion" skillId="2" skillLvl="3" getLevel="25" levelUpSp="5500" />
		<skill skillName="Death Armor Mastery" skillId="45354" skillLvl="5" getLevel="25" levelUpSp="5500" />
		<skill skillName="Death Sword Mastery" skillId="45353" skillLvl="5" getLevel="25" levelUpSp="5500" />
		<skill skillName="Enhanced Weapon" skillId="255" skillLvl="10" getLevel="25" levelUpSp="5500" />
		<skill skillName="Ability to Attack" skillId="77" skillLvl="2" getLevel="25" levelUpSp="5500" />
		<skill skillName="Emergency Rescue" skillId="70" skillLvl="4" getLevel="25" levelUpSp="5500" />

		<!-- Skills Lv26 -->
		<skill skillName="Confusion" skillId="2" skillLvl="4" getLevel="26" levelUpSp="5500" />
		<skill skillName="Punishment" skillId="45301" skillLvl="2" getLevel="26" levelUpSp="5500" />
		<skill skillName="Enhanced Weapon" skillId="255" skillLvl="11" getLevel="26" levelUpSp="5500" />

		<!-- Skills Lv27 -->
		<skill skillName="Confusion" skillId="2" skillLvl="5" getLevel="27" levelUpSp="5500" />
		<skill skillName="Enhanced Weapon" skillId="255" skillLvl="12" getLevel="27" levelUpSp="5500" />

		<!-- Skills Lv28 -->
		<skill skillName="Confusion" skillId="2" skillLvl="6" getLevel="28" levelUpSp="5500" />
		<skill skillName="Confusion" skillId="2" skillLvl="7" getLevel="28" levelUpSp="5500" />
		<skill skillName="Enhanced Weapon" skillId="255" skillLvl="13" getLevel="28" levelUpSp="5500" />

		<!-- Skills Lv29 -->
		<skill skillName="Confusion" skillId="2" skillLvl="8" getLevel="29" levelUpSp="10000" />
		<skill skillName="Enhanced Weapon" skillId="255" skillLvl="14" getLevel="29" levelUpSp="10000" />

		<!-- Skills Lv30 -->
		<skill skillName="Confusion" skillId="2" skillLvl="9" getLevel="30" levelUpSp="10000" />
		<skill skillName="Death Armor Mastery" skillId="45354" skillLvl="6" getLevel="30" levelUpSp="10000" />
		<skill skillName="Death Sword Mastery" skillId="45353" skillLvl="6" getLevel="30" levelUpSp="10000" />
		<skill skillName="Empower" skillId="45105" skillLvl="2" getLevel="30" levelUpSp="11000" />
		<skill skillName="Wild Magic" skillId="45106" skillLvl="1" getLevel="30" levelUpSp="11000" />
		<skill skillName="Berserker Spirit" skillId="45112" skillLvl="1" getLevel="30" levelUpSp="11000" />
		<skill skillName="Wind Walk" skillId="45107" skillLvl="2" getLevel="30" levelUpSp="11000" />
		<skill skillName="Magic Barrier" skillId="45108" skillLvl="1" getLevel="30" levelUpSp="11000" />
		<skill skillName="Enhanced Weapon" skillId="255" skillLvl="15" getLevel="30" levelUpSp="10000" />
		<skill skillName="Acumen" skillId="45104" skillLvl="2" getLevel="30" levelUpSp="11000" />
		<skill skillName="Roar of Death" skillId="45328" skillLvl="1" getLevel="30" levelUpSp="10000" />
		<skill skillName="Focus" skillId="45109" skillLvl="2" getLevel="30" levelUpSp="11000" />
		<skill skillName="Clarity" skillId="45113" skillLvl="2" getLevel="30" levelUpSp="11000" />
		<skill skillName="Death Whisper" skillId="45110" skillLvl="2" getLevel="30" levelUpSp="11000" />
		<skill skillName="Emergency Rescue" skillId="70" skillLvl="5" getLevel="30" levelUpSp="10000" />

		<!-- Skills Lv31 -->
		<skill skillName="Confusion" skillId="2" skillLvl="10" getLevel="31" levelUpSp="10000" />

		<!-- Skills Lv32 -->
		<skill skillName="Confusion" skillId="2" skillLvl="11" getLevel="32" levelUpSp="10000" />
		<skill skillName="Confusion" skillId="2" skillLvl="12" getLevel="32" levelUpSp="10000" />
		<skill skillName="Punishment" skillId="45301" skillLvl="3" getLevel="32" levelUpSp="10000" />
		<skill skillName="Emergency Rescue" skillId="70" skillLvl="6" getLevel="32" levelUpSp="10000" />
		<skill skillName="Power Break" skillId="115" skillLvl="1" getLevel="32" levelUpSp="10000"/>

		<!-- Skills Lv33 -->
		<skill skillName="Confusion" skillId="2" skillLvl="13" getLevel="33" levelUpSp="20000" />

		<!-- Skills Lv34 -->
		<skill skillName="Confusion" skillId="2" skillLvl="14" getLevel="34" levelUpSp="20000" />
		<skill skillName="Emergency Rescue" skillId="70" skillLvl="7" getLevel="34" levelUpSp="20000" />

		<!-- Skills Lv35 -->
		<skill skillName="Confusion" skillId="2" skillLvl="15" getLevel="35" levelUpSp="20000" />
		<skill skillName="Dark Elven Spirit" skillId="129" skillLvl="2" getLevel="35" levelUpSp="20000" />
		<skill skillName="Death Armor Mastery" skillId="45354" skillLvl="7" getLevel="35" levelUpSp="20000" />
		<skill skillName="Death Sword Mastery" skillId="45353" skillLvl="7" getLevel="35" levelUpSp="20000" />

		<!-- Skills Lv36 -->
		<skill skillName="Confusion" skillId="2" skillLvl="16" getLevel="36" levelUpSp="20000" />
		<skill skillName="Confusion" skillId="2" skillLvl="17" getLevel="36" levelUpSp="20000" />
		<skill skillName="Emergency Rescue" skillId="70" skillLvl="8" getLevel="36" levelUpSp="20000" />
		<skill skillName="Power Break" skillId="115" skillLvl="2" getLevel="36" levelUpSp="20000" />

		<!-- Skills Lv37 -->
		<skill skillName="Confusion" skillId="2" skillLvl="18" getLevel="37" levelUpSp="20000" />

		<!-- Skills Lv38 -->
		<skill skillName="Confusion" skillId="2" skillLvl="19" getLevel="38" levelUpSp="20000" />
		<skill skillName="Punishment" skillId="45301" skillLvl="4" getLevel="38" levelUpSp="20000" />
		<skill skillName="Emergency Rescue" skillId="70" skillLvl="9" getLevel="38" levelUpSp="20000" />

		<!-- Skills Lv39 -->
		<skill skillName="Confusion" skillId="2" skillLvl="20" getLevel="39" levelUpSp="20000" />
		
	</skillTree>
</list>

=== L2jOrg/Datapack/data/skillTrees/StartingClass/ElvenMystic.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org ../../xsd/skillTrees.xsd">
	<skillTree type="classSkillTree" classId="25">
	
		<!-- Starting Skills Lv1 -->
		<skill name="Magician's Attitude" id="118" level="1" required-level="1" auto-learn="true" />
		<skill name="Armor Mastery" id="244" level="1" required-level="1" auto-learn="true" />
		<skill name="Weapon Mastery" id="249" level="1" required-level="1" auto-learn="true" />
		<skill name="Fireball" id="1147" level="1" required-level="1" auto-learn="true" />
		<skill name="Wind Strike" id="1177" level="1" required-level="1" auto-learn="true" />
		<skill name="Ice Bolt" id="1184" level="1" required-level="1" auto-learn="true" />
		<skill name="Self Heal" id="1216" level="1" required-level="1" auto-learn="true" />
		<skill name="Children of Eva" id="53008" level="1" required-level="1" auto-learn="true" />
		<skill name="Mana Recovery" id="214" level="1" required-level="1" auto-learn="true" />
		<skill name="Spellcraft" id="163" level="1" required-level="1" auto-learn="true" />

		<!-- Inventory Expansion -->		
		<skill name="Extra Inventory" id="1372" level="1" required-level="1" >
			<item id="92004" count="1"/> <!-- Inventory Expansion Ticket Lv. 1 -->
		</skill>
		<skill name="Extra Inventory" id="1372" level="2" required-level="1" >
			<item id="92005" count="1"/>   <!-- Inventory Expansion Ticket Lv. 2 -->
		</skill>
		<skill name="Extra Inventory" id="1372" level="3" required-level="1" >
			<item id="92006" count="1"/>  <!-- Inventory Expansion Ticket Lv. 3  -->
		</skill>
		<skill name="Extra Inventory" id="1372" level="4" required-level="1" >
			<item id="92007" count="1"/>  <!-- Inventory Expansion Ticket Lv. 4 -->
		</skill>
		<skill name="Extra Inventory" id="1372" level="5" required-level="1" >
			<item id="92008" count="1"/>  <!-- Inventory Expansion Ticket Lv. 5 -->
		</skill>
		
		<!-- Skills Lv2 -->		
		<skill name="Shield" id="1040" level="1" required-level="2" sp="5" />

		<!-- Skills Lv3 -->
		<skill name="Heal" id="1011" level="1" required-level="3" sp="10" />
		<skill name="Might" id="1068" level="1" required-level="3" sp="5" />

		<!-- Skills Lv4 -->
		<skill name="Anti Magic" id="146" level="1" required-level="4" sp="15" />
		<skill name="Ice Bolt" id="1184" level="2" required-level="4" sp="15" />
		<skill name="Wind Strike" id="1177" level="2" required-level="4" sp="15" />

		<!-- Skills Lv5 -->
		<skill name="Heal" id="1011" level="2" required-level="5" sp="20" />
		<skill name="Self Heal" id="1216" level="2" required-level="5" sp="20" />

		<!-- Skills Lv7 -->
		<skill name="Anti Magic" id="146" level="2" required-level="7" sp="25" />
		<skill name="Cure" id="1012" level="1" required-level="7" sp="25" />
		<skill name="Ice Bolt" id="1184" level="3" required-level="7" sp="25" />
		<skill name="Heal" id="1011" level="3" required-level="7" sp="25" />
		<skill name="Wind Strike" id="1177" level="3" required-level="7" sp="25" />

		<!-- Skills Lv10 -->
		<skill name="Battle Heal" id="1015" level="1" required-level="10" sp="160" />
		<skill name="Group Heal" id="1027" level="1" required-level="10" sp="160" />
		<skill name="Heal" id="1011" level="4" required-level="10" sp="160" />
		<skill name="Fireball" id="1147" level="2" required-level="10" sp="160" />
		<skill name="Wind Shackle" id="1206" level="1" required-level="10" sp="200" />
		<skill name="Weakness" id="1164" level="1" required-level="10" sp="200" />

		<!-- Skills Lv11 -->
		<skill name="Anti Magic" id="146" level="3" required-level="11" sp="160" />
		<skill name="Armor Mastery" id="244" level="2" required-level="11" sp="160" />
		<skill name="Ice Bolt" id="1184" level="4" required-level="11" sp="160" />
		<skill name="Wind Strike" id="1177" level="4" required-level="11" sp="160" />

		<!-- Skills Lv12 -->
		<skill name="Battle Heal" id="1015" level="2" required-level="12" sp="190" />
		<skill name="Group Heal" id="1027" level="2" required-level="12" sp="190" />
		<skill name="Heal" id="1011" level="5" required-level="12" sp="190" />

		<!-- Skills Lv14 -->
		<skill name="Anti Magic" id="146" level="4" required-level="14" sp="190" />
		<skill name="Battle Heal" id="1015" level="3" required-level="14" sp="190" />
		<skill name="Armor Mastery" id="244" level="3" required-level="14" sp="190" />
		<skill name="Weapon Mastery" id="249" level="2" required-level="14" sp="190" />
		<skill name="Group Heal" id="1027" level="3" required-level="14" sp="190" />
		<skill name="Ice Bolt" id="1184" level="5" required-level="14" sp="190" />
		<skill name="Heal" id="1011" level="6" required-level="14" sp="190" />
		<skill name="Wind Strike" id="1177" level="5" required-level="14" sp="190" />

		<!-- Skills Lv15 -->
		<skill name="Fireball" id="1147" level="3" required-level="15" sp="200" />
		<skill name="Self Heal" id="1216" level="3" required-level="15" sp="250" />

	</skillTree>
</list>
