=== L2jOrg/Datapack/data/xsd/skillTrees.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://l2j.org"
		   xmlns="http://l2j.org"
		   elementFormDefault="qualified">

	<xs:include schemaLocation="common.xsd"/>

	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="skillTree" type="SkillTreeType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="SkillTreeType">
		<xs:sequence>
			<xs:element name="skill" type="LearnSkillType" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="classId" type="ClassId"/>
		<xs:attribute name="parentClassId" type="ClassId"/>
		<xs:attribute name="type" type="TreeType" use="required"/>
		<xs:attribute name="race" type="Race"/>
	</xs:complexType>

	<xs:complexType name="LearnSkillType">
		<xs:sequence>
			<xs:element name="social-status" type="SocialStatus" minOccurs="0"/>
			<xs:element name="residenceId" type="xs:positiveInteger" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="race" type="Race" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="replace-skill" type="SkillInfo" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="item"  type="ItemInfo" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="autoGet" type="xs:boolean" default="false"/>  
		<xs:attribute name="required-level" type="xs:positiveInteger"/>
		<xs:attribute name="learnedByNpc" type="xs:boolean" />
		<xs:attribute name="levelUpSp" type="xs:long" />
		<xs:attribute name="skillId" type="xs:positiveInteger" use="required" />
		<xs:attribute name="skillLvl" type="xs:positiveInteger" use="required" />
		<xs:attribute name="skillName" type="xs:normalizedString" use="required" />
	</xs:complexType>

	<xs:simpleType name="TreeType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="abilitySkillTree" />
			<xs:enumeration value="alchemySkillTree" />
			<xs:enumeration value="classSkillTree" />
			<xs:enumeration value="collectSkillTree" />
			<xs:enumeration value="fishingSkillTree" />
			<xs:enumeration value="gameMasterSkillTree" />
			<xs:enumeration value="heroSkillTree" />
			<xs:enumeration value="pledgeSkillTree" />
			<xs:enumeration value="raceSkillTree" />
			<xs:enumeration value="transferSkillTree" />
			<xs:enumeration value="transformSkillTree" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== L2jOrg/Datapack/data/skillTrees/3rdClass/Swordmuse.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org ../../xsd/skillTrees.xsd">
	<skillTree type="classSkillTree" classId="100" parentClassId="21">
		<skill name="White Guardian" id="54102" level="1" required-level="80" >
			<item id="92401"/>
		</skill>
		<skill name="Arrest" id="402" level="11" required-level="76" sp="10200000" />
		<skill name="Sword/Blunt Weapon Mastery" id="217" level="46" required-level="76" sp="10200000" />
		<skill name="Heavy Armor Mastery" id="232" level="53" required-level="76" sp="10200000" />
		<skill name="Magic Resistance" id="147" level="52" required-level="76" sp="10200000" />
		<skill name="Entangle" id="102" level="17" required-level="76" sp="10200000" />
		<skill name="Charm" id="15" level="53" required-level="76" sp="10200000" />
		<skill name="Sword Symphony" id="98" level="6" required-level="76" sp="10200000" />
		<skill name="Deadly Strike" id="1632" level="1" required-level="76" sp="10200000" />
		<skill name="Divine Inspiration" id="1405" level="3" required-level="76" sp="10200000">
			<item id="8620"/> <!-- Ancient Book: Divine Inspiration (Manuscript) -->
		</skill>
		<skill name="Divine Inspiration" id="1405" level="4" required-level="76" sp="10200000">
			<item id="8621"/> <!-- Ancient Book: Divine Inspiration (Original Version) -->
		</skill>
		<skill name="Mount Pegasus" id="1834" level="1" required-level="76">
			<item id="90039"/> <!-- Spellbook: Mount Pegasus -->
		</skill>
		<skill name="Glory Ability" id="45361" level="1" required-level="86">
			<item id="94046"/> <!-- Spellbook: Glory Ability Lv. 1 -->
		</skill>
		<skill name="Mount White Wings" id="54200" level="1" required-level="87">
			<item id="93059"/> <!-- Spellbook: Summon White Wings -->
		</skill>	
		<skill name="Mount Shining Lady" id="54202" level="1" required-level="89">
			<item id="93061"/> <!-- Spellbook: Summon Silver Saint -->
		</skill>
		
		<skill name="Sword/Blunt Weapon Mastery" id="217" level="47" required-level="77" sp="10200000" />
		<skill name="Heavy Armor Mastery" id="232" level="54" required-level="77" sp="10200000" />
		<skill name="Magic Resistance" id="147" level="53" required-level="77" sp="10200000" />
		<skill name="Deadly Strike" id="1632" level="2" required-level="77" sp="10200000" />
		<skill name="Song of Renewal" id="349" level="1" required-level="77" sp="10200000">
			<item id="90090"/> <!-- Scroll: Song of Renewal -->
		</skill>
		
		<skill name="Arrest" id="402" level="12" required-level="78" sp="23800000" />
		<skill name="Sword/Blunt Weapon Mastery" id="217" level="48" required-level="78" sp="23800000" />
		<skill name="Heavy Armor Mastery" id="232" level="55" required-level="78" sp="23800000" />
		<skill name="Magic Resistance" id="147" level="54" required-level="78" sp="23800000" />
		<skill name="Entangle" id="102" level="18" required-level="78" sp="23800000" />
		<skill name="Charm" id="15" level="54" required-level="78" sp="23800000" />
		<skill name="Deadly Strike" id="1632" level="3" required-level="78" sp="23800000" />
		<skill name="Champion Song" id="364" level="1" required-level="78" sp="23800000">
			<item id="90091"/> <!-- Scroll: Champion Song -->
		</skill>
		
		<skill name="Song of Silence" id="437" level="1" required-level="79" sp="23800000">
			<item id="90092"/>  <!-- Scroll: Song of Silence -->
		</skill>
		
		<skill name="Sword/Blunt Weapon Mastery" id="217" level="49" required-level="80" sp="23800000" />
		<skill name="Heavy Armor Mastery" id="232" level="56" required-level="80" sp="23800000" />
		<skill name="Magic Resistance" id="147" level="55" required-level="80" sp="23800000" />
		<skill name="Sword Symphony" id="98" level="7" required-level="80" sp="23800000" />
		<skill name="Deadly Strike" id="1632" level="4" required-level="80" sp="23800000" />
		<skill name="Song of Purification" id="914" level="1" required-level="80" sp="23800000">
			<item id="90093"/> <!-- Scroll: Song of Purification -->
		</skill>

		<skill name="Sword/Blunt Weapon Mastery" id="217" level="50" required-level="81" sp="160000000" />
		<skill name="Heavy Armor Mastery" id="232" level="57" required-level="81" sp="160000000" />
		<skill name="Magic Resistance" id="147" level="56" required-level="81" sp="160000000" />
		<skill name="Song of Wind" id="268" level="2" required-level="81" sp="160000000" />
		<skill name="Song of Silence" id="437" level="2" required-level="81" sp="160000000" />
		<skill name="Deadly Strike" id="1632" level="5" required-level="81" sp="160000000" />

		<skill name="Sword/Blunt Weapon Mastery" id="217" level="51" required-level="82" sp="170000000" />
		<skill name="Heavy Armor Mastery" id="232" level="58" required-level="82" sp="170000000" />
		<skill name="Magic Resistance" id="147" level="57" required-level="82" sp="170000000" />
		<skill name="Song of Vitality" id="304" level="2" required-level="82" sp="170000000" />
		<skill name="Deadly Strike" id="1632" level="6" required-level="82" sp="170000000" />

		<skill name="Sword/Blunt Weapon Mastery" id="217" level="52" required-level="83" sp="240000000" />
		<skill name="Heavy Armor Mastery" id="232" level="59" required-level="83" sp="240000000" />
		<skill name="Magic Resistance" id="147" level="58" required-level="83" sp="240000000" />
		<skill name="Hunter's Song" id="269" level="2" required-level="83" sp="240000000" />
		<skill name="Song of Silence" id="437" level="3" required-level="83" sp="240000000" />
		<skill name="Deadly Strike" id="1632" level="7" required-level="83" sp="240000000" />

		<skill name="Sword/Blunt Weapon Mastery" id="217" level="53" required-level="84" sp="240000000" />
		<skill name="Heavy Armor Mastery" id="232" level="60" required-level="84" sp="240000000" />
		<skill name="Magic Resistance" id="147" level="59" required-level="84" sp="240000000" />
		<skill name="Song of Renewal" id="349" level="2" required-level="84" sp="240000000" />
		<skill name="Sword Symphony" id="98" level="8" required-level="84" sp="240000000" />
		<skill name="Deadly Strike" id="1632" level="8" required-level="84" sp="240000000" />
		
		<skill name="Sword/Blunt Weapon Mastery" id="217" level="54" required-level="85" sp="840000000" />
		<skill name="Sword/Blunt Weapon Mastery" id="217" level="55" required-level="86" sp="924000000" />
		<skill name="Sword/Blunt Weapon Mastery" id="217" level="56" required-level="87" sp="1016400000" />
		<skill name="Sword/Blunt Weapon Mastery" id="217" level="57" required-level="88" sp="1118040000" />
		<skill name="Sword/Blunt Weapon Mastery" id="217" level="58" required-level="89" sp="1229844000" />
		<skill name="Sword/Blunt Weapon Mastery" id="217" level="59" required-level="90" sp="1352828400" />
		<skill name="Heavy Armor Mastery" id="232" level="61" required-level="85" sp="840000000" />
		<skill name="Heavy Armor Mastery" id="232" level="62" required-level="86" sp="924000000" />
		<skill name="Heavy Armor Mastery" id="232" level="63" required-level="87" sp="1016400000" />
		<skill name="Heavy Armor Mastery" id="232" level="64" required-level="88" sp="1118040000" />
		<skill name="Heavy Armor Mastery" id="232" level="65" required-level="89" sp="1229844000" />
		<skill name="Heavy Armor Mastery" id="232" level="66" required-level="90" sp="1352828400" />
		<skill name="Magic Resistance" id="147" level="60" required-level="85" sp="840000000" />
		<skill name="Magic Resistance" id="147" level="61" required-level="86" sp="924000000" />
		<skill name="Magic Resistance" id="147" level="62" required-level="87" sp="1016400000" />
		<skill name="Magic Resistance" id="147" level="63" required-level="88" sp="1118040000" />
		<skill name="Magic Resistance" id="147" level="64" required-level="89" sp="1229844000" />
		<skill name="Magic Resistance" id="147" level="65" required-level="90" sp="1352828400" />
	</skillTree>
</list>

=== L2jOrg/Datapack/data/skillTrees/1stClass/ElvenWizard.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org ../../xsd/skillTrees.xsd">
	<skillTree type="classSkillTree" classId="26" parentClassId="25">
		<skill name="Anti Magic" id="146" level="5" required-level="20" sp="600" />
		<skill name="Anti Magic" id="146" level="6" required-level="20" sp="600" />
		<skill name="Quick Recovery" id="164" level="1" required-level="20" sp="600" />
		<skill name="Robe Mastery" id="234" level="1" required-level="20" sp="600" />
		<skill name="Robe Mastery" id="234" level="2" required-level="20" sp="600" />
		<skill name="Weapon Mastery" id="249" level="3" required-level="20" sp="600" />
		<skill name="Aqua Swirl" id="1175" level="1" required-level="20" sp="600" />
		<skill name="Aqua Swirl" id="1175" level="2" required-level="20" sp="600" />
		<skill name="Ice Bolt" id="1184" level="5" required-level="20" sp="600" />
		<skill name="Ice Bolt" id="1184" level="6" required-level="20" sp="600" />
		<skill name="Servitor Heal" id="1127" level="1" required-level="20" sp="600" />
		<skill name="Servitor Heal" id="1127" level="2" required-level="20" sp="600" />
		<skill name="Servitor Heal" id="1127" level="3" required-level="20" sp="600" />
		<skill name="Summon Boxer the Unicorn" id="1226" level="1" required-level="20" sp="600" />
		<skill name="Summon Mirage the Unicorn" id="1227" level="1" required-level="20" sp="600" />
		<skill name="Curse Weakness" id="1164" level="2" required-level="20" sp="600" />
		<skill name="Aura Burn" id="1172" level="1" required-level="20" sp="600" />
		<skill name="Aura Burn" id="1172" level="2" required-level="20" sp="600" />
		<skill name="Boost Mana" id="213" level="1" required-level="20" sp="600" />
		<skill name="Flame Strike" id="1181" level="1" required-level="20" sp="600" />
		<skill name="Higher Mana Gain" id="285" level="1" required-level="20" sp="600" />
		<skill name="Higher Mana Gain" id="285" level="2" required-level="20" sp="600" />
		<skill name="Energy Bolt" id="1274" level="1" required-level="20" sp="600" />
		<skill name="Concentration" id="1078" level="1" required-level="20" sp="600">
			<item id="1399"/>
		</skill>

		<skill name="Anti Magic" id="146" level="7" required-level="23" sp="2300" />
		<skill name="Robe Mastery" id="234" level="3" required-level="23" sp="2300" />
		<skill name="Weapon Mastery" id="249" level="4" required-level="23" sp="2300" />
		<skill name="Aqua Swirl" id="1175" level="3" required-level="23" sp="2300" />
		<skill name="Servitor Heal" id="1127" level="4" required-level="23" sp="2300" />
		<skill name="Aura Burn" id="1172" level="3" required-level="23" sp="2300" />
		<skill name="Higher Mana Gain" id="285" level="3" required-level="23" sp="2300" />
		<skill name="Sleep" id="1069" level="1" required-level="23" sp="2300">
			<item id="1394"/>
		</skill>
		
		<skill name="Servitor Heal" id="1127" level="5" required-level="24" sp="2300" />
		<skill name="Sleep" id="1069" level="2" required-level="24" sp="2300" />

		<skill name="Anti Magic" id="146" level="8" required-level="25" sp="2300" />
		<skill name="Fast Mana Recovery" id="229" level="1" required-level="25" sp="2300" />
		<skill name="Fast Spell Casting" id="228" level="1" required-level="25" sp="2300" />
		<skill name="Robe Mastery" id="234" level="4" required-level="25" sp="2300" />
		<skill name="Weapon Mastery" id="249" level="5" required-level="25" sp="2300" />
		<skill name="Aqua Swirl" id="1175" level="4" required-level="25" sp="2300" />
		<skill name="Servitor Heal" id="1127" level="6" required-level="25" sp="2300" />
		<skill name="Servitor Recharge" id="1126" level="1" required-level="25" sp="2300" />
		<skill name="Servitor Recharge" id="1126" level="2" required-level="25" sp="2300" />
		<skill name="Summon Boxer the Unicorn" id="1226" level="2" required-level="25" sp="2300" />
		<skill name="Summon Mirage the Unicorn" id="1227" level="2" required-level="25" sp="2300" />
		<skill name="Curse Weakness" id="1164" level="3" required-level="25" sp="2300" />
		<skill name="Body To Mind" id="1157" level="1" required-level="25" sp="2300" />
		<skill name="Aura Burn" id="1172" level="4" required-level="25" sp="2300" />
		<skill name="Solar Spark" id="1264" level="1" required-level="25" sp="2300" />
		<skill name="Flame Strike" id="1181" level="2" required-level="25" sp="2300" />
		<skill name="Higher Mana Gain" id="285" level="4" required-level="25" sp="2300" />
		<skill name="Sleep" id="1069" level="3" required-level="25" sp="2300" />
		<skill name="Energy Bolt" id="1274" level="2" required-level="25" sp="2300" />
		
		<skill name="Anti Magic" id="146" level="9" required-level="28" sp="5700" />
		<skill name="Robe Mastery" id="234" level="5" required-level="28" sp="5700" />
		<skill name="Weapon Mastery" id="249" level="6" required-level="28" sp="5700" />
		<skill name="Aqua Swirl" id="1175" level="5" required-level="28" sp="5700" />
		<skill name="Servitor Heal" id="1127" level="7" required-level="28" sp="5700" />
		<skill name="Aura Burn" id="1172" level="5" required-level="28" sp="5700" />
		<skill name="Higher Mana Gain" id="285" level="5" required-level="28" sp="5700" />
		<skill name="Sleep" id="1069" level="4" required-level="28" sp="5700" />
		
		<skill name="Servitor Heal" id="1127" level="8" required-level="29" sp="5700" />
		<skill name="Sleep" id="1069" level="5" required-level="29" sp="5700" />

		<skill name="Anti Magic" id="146" level="10" required-level="30" sp="5700" />
		<skill name="Quick Recovery" id="164" level="2" required-level="30" sp="5700" />
		<skill name="Robe Mastery" id="234" level="6" required-level="30" sp="5700" />
		<skill name="Weapon Mastery" id="249" level="7" required-level="30" sp="5700" />
		<skill name="Aqua Swirl" id="1175" level="6" required-level="30" sp="5700" />
		<skill name="Concentration" id="1078" level="2" required-level="30" sp="5700" />
		<skill name="Servitor Heal" id="1127" level="9" required-level="30" sp="5700" />
		<skill name="Servitor Recharge" id="1126" level="3" required-level="30" sp="5700" />
		<skill name="Servitor Recharge" id="1126" level="4" required-level="30" sp="5700" />
		<skill name="Summon Boxer the Unicorn" id="1226" level="3" required-level="30" sp="5700" />
		<skill name="Summon Mirage the Unicorn" id="1227" level="3" required-level="30" sp="5700" />
		<skill name="Curse Weakness" id="1164" level="4" required-level="30" sp="5700" />
		<skill name="Aura Burn" id="1172" level="6" required-level="30" sp="5700" />
		<skill name="Solar Spark" id="1264" level="2" required-level="30" sp="5700" />
		<skill name="Boost Mana" id="213" level="2" required-level="30" sp="5700" />
		<skill name="Flame Strike" id="1181" level="3" required-level="30" sp="5700" />
		<skill name="Higher Mana Gain" id="285" level="6" required-level="30" sp="5700" />
		<skill name="Sleep" id="1069" level="6" required-level="30" sp="5700" />
		<skill name="Energy Bolt" id="1274" level="3" required-level="30" sp="5700" />
		
		<skill name="Anti Magic" id="146" level="11" required-level="33" sp="13000" />
		<skill name="Robe Mastery" id="234" level="7" required-level="33" sp="13000" />
		<skill name="Weapon Mastery" id="249" level="8" required-level="33" sp="13000" />
		<skill name="Aqua Swirl" id="1175" level="7" required-level="33" sp="13000" />
		<skill name="Servitor Heal" id="1127" level="10" required-level="33" sp="13000" />
		<skill name="Aura Burn" id="1172" level="7" required-level="33" sp="13000" />
		<skill name="Higher Mana Gain" id="285" level="7" required-level="33" sp="13000" />
		<skill name="Sleep" id="1069" level="7" required-level="33" sp="13000" />
		
		<skill name="Servitor Heal" id="1127" level="11" required-level="34" sp="13000" />
		<skill name="Sleep" id="1069" level="8" required-level="34" sp="13000" />

		<skill name="Anti Magic" id="146" level="12" required-level="35" sp="13000" />
		<skill name="Fast HP Recovery" id="212" level="1" required-level="35" sp="13000" />
		<skill name="Fast Mana Recovery" id="229" level="2" required-level="35" sp="13000" />
		<skill name="Robe Mastery" id="234" level="8" required-level="35" sp="13000" />
		<skill name="Weapon Mastery" id="249" level="9" required-level="35" sp="13000" />
		<skill name="Aqua Swirl" id="1175" level="8" required-level="35" sp="13000" />
		<skill name="Servitor Heal" id="1127" level="12" required-level="35" sp="13000" />
		<skill name="Servitor Recharge" id="1126" level="5" required-level="35" sp="13000" />
		<skill name="Servitor Recharge" id="1126" level="6" required-level="35" sp="13000" />
		<skill name="Summon Boxer the Unicorn" id="1226" level="4" required-level="35" sp="13000" />
		<skill name="Summon Mirage the Unicorn" id="1227" level="4" required-level="35" sp="13000" />
		<skill name="Curse Weakness" id="1164" level="5" required-level="35" sp="13000" />
		<skill name="Aura Burn" id="1172" level="8" required-level="35" sp="13000" />
		<skill name="Solar Spark" id="1264" level="3" required-level="35" sp="13000" />
		<skill name="Servitor Magic Boost" id="1145" level="1" required-level="35" sp="13000" />
		<skill name="Higher Mana Gain" id="285" level="8" required-level="35" sp="13000" />
		<skill name="Sleep" id="1069" level="9" required-level="35" sp="13000" />
		<skill name="Energy Bolt" id="1274" level="4" required-level="35" sp="13000" />
	</skillTree>
</list>

=== L2jOrg/Datapack/data/skillTrees/1stClass/Warden.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org ../../xsd/skillTrees.xsd">
    <skillTree type="classSkillTree" classId="126" parentClassId="192">

        <skill skillName="Armor Mastery" skillId="464" skillLvl="2" required-level="20" levelUpSp="1000" />
        <skill skillName="Light Armor Mastery" skillId="465" skillLvl="1" required-level="20" levelUpSp="1000" />
        <skill skillName="Weapon Mastery" skillId="463" skillLvl="2" required-level="20" levelUpSp="1000" />
        <skill skillName="Bow Mastery" skillId="767" skillLvl="1" required-level="20" levelUpSp="1000" />
        <skill skillName="Light Master" skillId="45178" skillLvl="1" required-level="20"  />
        <skill skillName="Long Shot" skillId="113" skillLvl="1" required-level="20" levelUpSp="1000" />
        <skill skillName="Shine Soul Finding" skillId="393" skillLvl="1" required-level="20" levelUpSp="1000" />
        <skill skillName="Dash" skillId="4" skillLvl="1" required-level="20" levelUpSp="1000" />
        <skill skillName="Twin Shot" skillId="45168" skillLvl="1" required-level="20" levelUpSp="1000" />

        <skill skillName="Magic Immunity" skillId="466" skillLvl="1" required-level="25" levelUpSp="5500" />

        <skill skillName="Ultimate Escape" skillId="622" skillLvl="1" required-level="28" levelUpSp="5500" />

        <skill skillName="Light Armor Mastery" skillId="465" skillLvl="2" required-level="30" levelUpSp="10000" />
        <skill skillName="Bow Mastery" skillId="767" skillLvl="2" required-level="30" levelUpSp="10000" />
        <skill skillName="Twin Shot" skillId="45168" skillLvl="2" required-level="30" levelUpSp="10000" />

        <skill skillName="Rapid Shot" skillId="99" skillLvl="1" required-level="32" levelUpSp="10000"/>
        <skill skillName="Death Mark" skillId="1435" skillLvl="2" required-level="32" levelUpSp="10000"/>

    </skillTree>
</list>
