=== L2jOrg/Datapack/data/shop/l2-store.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://l2j.org"
           xmlns="http://l2j.org"
           elementFormDefault="qualified">

    <xs:include schemaLocation="shop-common.xsd"/>

    <xs:element name="list">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="product" type="Product" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Product">
        <xs:sequence>
            <xs:element name="item" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute type="xs:int" name="id" use="required"/>
                    <xs:attribute type="xs:int" name="count" default="1"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute type="xs:int" name="id" use="required"/>
        <xs:attribute type="xs:byte" name="category" use="required"/> <!-- 11 Supliers; 12 Cosmetic; 13 Vip; 14 Event; 15 Reward -->
        <xs:attribute type="xs:byte" name="payment-type" default="0"/> <!-- 0 NCoin; 3 Silver Coin -->
        <xs:attribute type="xs:int" name="price" use="required"/>
        <xs:attribute type="xs:byte" name="panel-type" default="0"/>
        <xs:attribute type="xs:byte" name="recommended" default="0"/>
        <xs:attribute type="xs:int" name="start-sale" default="0"/>
        <xs:attribute type="xs:int" name="end-sale" default="0"/>
        <xs:attribute type="xs:byte" name="days-of-week" default="127"/> <!-- bit flag -->
        <xs:attribute type="xs:byte" name="start-hour" default="0"/>
        <xs:attribute type="xs:byte" name="start-minute" default="0"/>
        <xs:attribute type="xs:byte" name="stop-hour" default="0"/>
        <xs:attribute type="xs:byte" name="stop-minute" default="0"/>
        <xs:attribute type="xs:byte" name="stock" default="0"/>
        <xs:attribute type="xs:byte" name="max-stock" default="-1"/>
        <xs:attribute type="xs:byte" name="sale-percent" default="0"/>
        <xs:attribute type="xs:byte" name="min-level" default="0"/>
        <xs:attribute type="xs:byte" name="max-level" default="0"/>
        <xs:attribute type="xs:byte" name="min-birthday" default="0"/>
        <xs:attribute type="xs:byte" name="max-birthday" default="0"/>
        <xs:attribute type="xs:byte" name="restriction-amount" default="0"/>
        <xs:attribute type="RestrictionPeriod" name="restriction-period" default="DAY"/>
        <xs:attribute type="xs:byte" name="available-count" default="0"/>
        <xs:attribute type="xs:byte" name="vip-tier" default="0"/>
        <xs:attribute type="xs:int" name="silver-coin" default="0"/>
        <xs:attribute type="xs:boolean" name="is-vip-gift" default="false"/>
    </xs:complexType>
</xs:schema>

=== L2jOrg/Datapack/data/shop/l2-store.xml
<?xml version='1.0' encoding='utf-8'?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org xsd/l2-store.xsd">
	<!-- Supplies 11 -->
	<product id="100091" category="11" price="25">
		<item id="29648" count="1" />
	</product>
	<product id="100259" category="11" price="15">
		<item id="70068" count="1" />
	</product>
	<product id="100281" category="11" price="1">
		<item id="13016" count="1" />
	</product>
	<product id="100282" category="11" price="50">
		<item id="13016" count="100" />
	</product>
	<product id="100283" category="11" price="2">
		<item id="20033" count="1" />
	</product>
	<product id="100284" category="11" price="80">
		<item id="13015" count="1" />
	</product>
	<product id="100308" category="11" price="8">
		<item id="90907" count="1" />
	</product>
	<product id="100309" category="11" price="200">
		<item id="90907" count="50" />
	</product>
	<product id="100313" category="11" price="800">
		<item id="92007" count="1" />
	</product>
	<product id="100316" category="11" price="25">
		<item id="71342" count="50" />
	</product>
	<product id="100352" category="11" price="70">
		<item id="91939" count="1" />
	</product>
	<product id="100386" category="11" price="50">
		<item id="49765" count="1" />
	</product>
	<product id="100388" category="11" price="50">
		<item id="71246" count="1" />
	</product>
	<product id="100389" category="11" price="2500">
		<item id="71250" count="1" />
	</product>
	<product id="100390" category="11" price="83">
		<item id="70268" count="1" />
	</product>
	<product id="100392" category="11" price="2000">
		<item id="70271" count="1" />
	</product>
	<product id="100393" category="11" price="240">
		<item id="90143" count="1" />
	</product>
	<product id="100520" category="11" price="60">
		<item id="71894" count="1" />
	</product>
	<product id="100521" category="11" price="60">
		<item id="92409" count="1" />
	</product>
	<product id="100523" category="11" price="200">
		<item id="46254" count="1" />
	</product>
	<product id="100524" category="11" price="40">
		<item id="91911" count="1" />
	</product>
	<product id="100525" category="11" price="32">
		<item id="90407" count="5" />
	</product>
	<product id="100526" category="11" price="60">
		<item id="49765" count="1" />
	</product>
	<product id="100527" category="11" price="200">
		<item id="90143" count="1" />
	</product>
	<product id="100529" category="11" price="48">
		<item id="29650" count="1" />
	</product>
	<product id="100530" category="11" price="1760" restriction-amount="5" restriction-period="EVER">
		<item id="72196" count="1" />
	</product>
	<!-- -->
	<!-- Cosmetic 12 -->
	<product id="100015" category="12" price="80">
		<item id="13307" count="1" />
	</product>
	<product id="100020" category="12" price="800">
		<item id="71251" count="1" />
	</product>
	<product id="100186" category="12" price="800">
		<item id="70977" count="1" />
	</product>
	<product id="100187" category="12" price="400">
		<item id="71252" count="1" />
	</product>
	<product id="100214" category="12" price="400">
		<item id="70557" count="1" />
	</product>
	<product id="100215" category="12" price="800">
		<item id="70985" count="1" />
	</product>
	<product id="100216" category="12" price="800">
		<item id="70981" count="1" />
	</product>
	<product id="100218" category="12" price="800">
		<item id="70978" count="1" />
	</product>
	<product id="100219" category="12" price="800">
		<item id="70986" count="1" />
	</product>
	<product id="100224" category="12" price="800">
		<item id="70979" count="1" />
	</product>
	<product id="100225" category="12" price="800">
		<item id="70980" count="1" />
	</product>
	<product id="100226" category="12" price="800">
		<item id="70983" count="1" />
	</product>
	<product id="100228" category="12" price="800">
		<item id="70987" count="1" />
	</product>
	<product id="100257" category="12" price="800">
		<item id="6408" count="1" />
	</product>
	<product id="100292" category="12" price="800">
		<item id="70968" count="1" />
	</product>
	<product id="100522" category="12" price="160">
		<item id="49662" count="1" />
	</product>
	<!-- VIP 13 Daily Gift -->
	<product id="100001" category="13" price="0" vip-tier="1" is-vip-gift="true" restriction-amount="1" restriction-period="DAY">
		<item id="29001" />
	</product>
	<product id="100002" category="13" price="0" vip-tier="2" is-vip-gift="true" restriction-amount="1" restriction-period="DAY">
		<item id="29002" />
	</product>
	<product id="100003" category="13" price="0" vip-tier="3" is-vip-gift="true" restriction-amount="1" restriction-period="DAY">
		<item id="29003" />
	</product>
	<product id="100004" category="13" price="0" vip-tier="4" is-vip-gift="true" restriction-amount="1" restriction-period="DAY">
		<item id="29004" />
	</product>
	<product id="100005" category="13" price="0" vip-tier="5" is-vip-gift="true" restriction-amount="1" restriction-period="DAY">
		<item id="29005" />
	</product>
	<product id="100006" category="13" price="0" vip-tier="6" is-vip-gift="true" restriction-amount="1" restriction-period="DAY">
		<item id="29006" />
	</product>
	<product id="100007" category="13" price="0" vip-tier="7" is-vip-gift="true" restriction-amount="1" restriction-period="DAY">
		<item id="29007" />
	</product>
	<product id="100008" category="13" price="0" vip-tier="8" is-vip-gift="true" restriction-amount="1" restriction-period="DAY">
		<item id="71963" />
	</product>
	<product id="100009" category="13" price="0" vip-tier="9" is-vip-gift="true" restriction-amount="1" restriction-period="DAY">
		<item id="71964" />
	</product>
	<product id="100010" category="13" price="0" vip-tier="10" is-vip-gift="true" restriction-amount="1" restriction-period="DAY">
		<item id="71965" />
	</product>
	<!-- VIP 13 -->
	<product id="100039" category="13" price="400" vip-tier="4">
		<item id="71253" count="1" />
	</product>
	<product id="100184" category="13" price="1200" vip-tier="3">
		<item id="70967" count="1" />
	</product>
	<product id="100185" category="13" price="680" vip-tier="2">
		<item id="70935" count="1" />
	</product>
	<product id="100217" category="13" price="680" vip-tier="2">
		<item id="70982" count="1" />
	</product>
	<product id="100227" category="13" price="600" vip-tier="2">
		<item id="70984" count="1" />
	</product>
	<product id="100251" category="13" price="0" vip-tier="2" restriction-amount="1" restriction-period="DAY">
		<item id="71416" count="1" />
	</product>
	<product id="100252" category="13" price="0" vip-tier="3" restriction-amount="1" restriction-period="DAY">
		<item id="70046" count="50" />
	</product>
	<product id="100265" category="13" price="0" vip-tier="2" restriction-amount="1" restriction-period="DAY">
		<item id="7126" count="1" />
	</product>
	<product id="100285" category="13" price="0" vip-tier="1" restriction-amount="1" restriction-period="DAY">
		<item id="90404" count="1" />
	</product>
	<product id="100391" category="13" price="1328" vip-tier="7" restriction-amount="1" restriction-period="DAY">
		<item id="70271" count="1" />
	</product>
	<product id="100428" category="13" price="0" vip-tier="2" restriction-amount="1" restriction-period="EVER">
		<item id="70192" count="1" />
	</product>
	<product id="100429" category="13" price="0" vip-tier="8" restriction-amount="1" restriction-period="MONTH">
		<item id="71951" count="30" />
	</product>
	<product id="100430" category="13" price="0" vip-tier="9" restriction-amount="1" restriction-period="MONTH">
		<item id="71952" count="30" />
	</product>
	<product id="100431" category="13" price="0" vip-tier="9" restriction-amount="1" restriction-period="MONTH">
		<item id="71953" count="1" />
	</product>
	<product id="100432" category="13" price="0" vip-tier="9" restriction-amount="1" restriction-period="MONTH">
		<item id="71954" count="1" />
	</product>
	<product id="100433" category="13" price="0" vip-tier="10" restriction-amount="1" restriction-period="EVER">
		<item id="71726" count="1" />
	</product>
	<product id="100462" category="13" price="0" vip-tier="4" restriction-amount="1" restriction-period="MONTH">
		<item id="71341" count="1" />
	</product>
	<product id="100508" category="13" price="0" panel-type="5" vip-tier="9" restriction-amount="1" restriction-period="MONTH">
		<item id="71955" count="1" />
	</product>
	<product id="100528" category="13" price="20" vip-tier="2">
		<item id="29649" count="1" />
	</product>
	<!-- Event 14 -->
	<product id="100022" category="14" price="2400">
		<item id="71264" count="1" />
	</product>
	<product id="100023" category="14" price="2400">
		<item id="71265" count="1" />
	</product>
	<product id="100425" category="14" price="80">
		<item id="91663" count="250" />
	</product>
	<product id="100426" category="14" price="2000">
		<item id="91663" count="6260" />
	</product>
	<product id="100427" category="14" price="8000">
		<item id="91663" count="25040" />
	</product>
	<product id="100434" category="14" price="0" restriction-amount="1" restriction-period="EVER">
		<item id="71833" count="1" />
	</product>
	<product id="100461" category="14" price="1" panel-type="5" restriction-amount="1" restriction-period="EVER">
		<item id="71336" count="1" />
	</product>
	<product id="100552" category="14" price="160" panel-type="5">
		<item id="70301" count="1" />
	</product>
	<product id="100553" category="14" price="1000" panel-type="5" vip-tier="4">
		<item id="70300" count="1" />
	</product>
	<product id="100570" category="14" price="40" panel-type="5">
		<item id="71879" count="1" />
	</product>
	<product id="100577" category="14" price="450" panel-type="6">
		<item id="72248" count="10" />
	</product>
	<product id="100578" category="14" price="4000" panel-type="6">
		<item id="72248" count="100" />
	</product>
	<product id="100579" category="14" price="1200" panel-type="5">
		<item id="71266" count="1" />
	</product>
	<!-- Reward Coins 15 -->
