=== L2jOrg/Datapack/data/shop/xsd/shop.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://l2j.org" xmlns="http://l2j.org" elementFormDefault="qualified">
	<xs:include schemaLocation="../../xsd/common.xsd" />
	<xs:include schemaLocation="shop-common.xsd" />
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element name="product" type="ProductInfo" />
			</xs:sequence>
			<xs:attribute name="chance-based" type="xs:boolean" default="false" />
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ProductInfo">
		<xs:sequence>
			<xs:element name="ingredient" type="ItemInfo" maxOccurs="4" />
			<xs:element name="production" type="ItemInfo" maxOccurs="3" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" use="required" />
		<xs:attribute name="index" type="xs:int" use="required" />
		<xs:attribute name="chance" type="xs:int" default="100" />
		<xs:attribute name="clan-level" type="xs:int" default="0" />
		<xs:attribute name="restriction-amount" type="xs:int" default="0" />
		<xs:attribute name="restriction-period" type="RestrictionPeriod" default="DAY" />
		<xs:attribute name="min-level" type="xs:positiveInteger" default="1" />
		<xs:attribute name="server-item-amount" type="xs:int" default="-1" />
		<xs:attribute name="expiration-date">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="202[1-9]-[01][0-9]-[0-3][0-9] [0-2][0-9]:[0-5][0-9]:[0-5][0-9]" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== L2jOrg/Datapack/data/shop/clan-shop.xml
<?xml version='1.0' encoding='utf-8'?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org xsd/shop.xsd">
	<product index="100" id="5300" clan-level="3" restriction-amount="15">
		<ingredient id="95570" count="8" />
		<production id="91641" />
	</product>
	<product index="100" id="5400" clan-level="4" restriction-amount="200">
		<ingredient id="95570" count="3" />
		<production id="91690" />
	</product>
	<product index="100" id="5500" clan-level="5" restriction-amount="4">
		<ingredient id="95570" count="200" />
		<production id="95636" />
	</product>
	<product index="100" id="5501" clan-level="5" restriction-amount="10">
		<ingredient id="95570" count="2" />
		<production id="95638" />
	</product>
	<product index="100" id="5600" clan-level="6" restriction-amount="4">
		<ingredient id="95570" count="200" />
		<production id="95637" />
	</product>
</list>

=== L2jOrg/Datapack/data/shop/l2-coin-shop.xml
<?xml version='1.0' encoding='utf-8'?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org xsd/shop.xsd">
	<!-- Category 0 -->
	<product index="3" id="10002">
		<ingredient id="91663" count="600" />
		<production id="91767" />
	</product>
	<product index="3" id="10001">
		<ingredient id="91663" count="600" />
		<production id="92020" />
	</product>
	<!-- Category 1 -->
	<product index="3" id="10012">
		<ingredient id="91663" count="300" />
		<production id="92004" />
	</product>
	<product index="3" id="10013">
		<ingredient id="91663" count="20" />
		<production id="92005" />
	</product>
	<product index="3" id="10014">
		<ingredient id="91663" count="10" />
		<production id="91689" />
	</product>
	<product index="3" id="10042">
		<ingredient id="91663" count="10" />
		<production id="90519" />
	</product>
	<product index="3" id="10043">
		<ingredient id="91663" count="10" />
		<production id="90183" />
	</product>
	<product index="3" id="10044">
		<ingredient id="91663" count="20" />
		<production id="49081" />
	</product>
	<product index="3" id="10003">
		<ingredient id="91663" count="700" />
		<production id="90311" />
	</product>
	<!-- Category 2 -->
	<product index="3" id="10016">
		<ingredient id="57" count="4000000" />
		<production id="92004" />
	</product>
	<product index="3" id="10017">
		<ingredient id="57" count="4000000" />
		<production id="92005" />
	</product>
	<product index="3" id="10018">
		<ingredient id="91663" count="2000" />
		<production id="92006" />
	</product>
	<product index="3" id="10019">
		<ingredient id="91663" count="2000" />
		<production id="92007" />
	</product>
	<product index="3" id="10020">
		<ingredient id="91663" count="2000" />
		<production id="92008" />
	</product>
	<product index="3" id="10021">
		<ingredient id="91663" count="4000" />
		<production id="91032" />
	</product>
	<product index="3" id="10022">
		<ingredient id="91663" count="4000" />
		<production id="91033" />
	</product>
	<product index="3" id="10023">
		<ingredient id="91663" count="4000" />
		<production id="91034" />
	</product>
	<product index="3" id="10024">
		<ingredient id="91663" count="4000" />
		<production id="91031" />
	</product>
	<product index="3" id="10065">
		<ingredient id="91663" count="10000" />
		<production id="32254" />
	</product>
	<product index="3" id="10025">
		<ingredient id="91663" count="5000" />
		<production id="32253" />
	</product>
	<product index="3" id="10026">
		<ingredient id="91663" count="1000" />
		<production id="32252" />
	</product>
	<product index="3" id="10027">
		<ingredient id="91663" count="400" />
		<production id="32251" />
	</product>
	<product index="3" id="10028">
		<ingredient id="91663" count="200" />
		<production id="32250" />
	</product>
	<!-- Category 3 -->
	<product index="3" id="10067" restriction-amount="1">
		<ingredient id="57" count="2000000" />
		<production id="91767" />
	</product>
	<product index="3" id="10066" restriction-amount="1">
		<ingredient id="57" count="2000000" />
		<production id="92020" />
	</product>
	<product index="3" id="10068" restriction-amount="1">
		<ingredient id="57" count="30000000" />
		<production id="94208" />
	</product>
	<product index="3" id="10071" restriction-amount="10">
		<ingredient id="57" count="200000" />
		<production id="94377" />
	</product>
	<!-- Category 4 -->
	<product index="3" id="10038" restriction-amount="1" expiration-date="2021-05-18 00:00:00">
		<ingredient id="57" count="100000" />
		<production id="71314" />
	</product>
</list>
