=== L2jOrg/Datapack/data/skills/skills.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://l2j.org"
           xmlns="http://l2j.org"
           elementFormDefault="qualified">

    <xs:include schemaLocation="../xsd/common.xsd"/>
    <xs:include schemaLocation="conditions.xsd"/>
    <xs:include schemaLocation="effects.xsd"/>

    <xs:element name="list">
        <xs:complexType>
            <xs:choice>
                <xs:element name="skill-config" type="SkillConfig"/>
                <xs:element name="skill" type="Skill" maxOccurs="unbounded" minOccurs="0"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Skill">
        <xs:sequence>
            <xs:element name="icon" type="MappedLevelToken"/>
            <xs:element name="attributes" type="SkillAttributes"/>
            <xs:element name="consume" type="Consume" minOccurs="0"/>
            <xs:element name="target" type="SkillTarget"/>
            <xs:element name="abnormal" type="Abnormal" minOccurs="0"/>
            <xs:element name="resist-abnormals" type="AbnormalTypeList" minOccurs="0"/>
            <xs:element name="channeling" type="Channeling" minOccurs="0"/>
            <xs:element name="conditions" type="Conditions" minOccurs="0"/>
            <xs:element name="effects" type="Effects" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="max-level" type="xs:positiveInteger" default="1"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="debuff" type="xs:boolean" default="false"/>
        <xs:attribute name="action" type="OperateType" default="P"/>
        <xs:attribute name="type" type="SkillType" default="PHYSIC"/>
    </xs:complexType>

    <xs:complexType name="Consume">
        <xs:sequence>
            <xs:element name="mana-init" type="MappedLevelInt" minOccurs="0"/>
            <xs:element name="mana" type="MappedLevelInt" minOccurs="0"/>
            <xs:element name="hp" type="MappedLevelInt" minOccurs="0"/>
            <xs:element name="item" type="MappedLevelInt" minOccurs="0"/>
            <xs:element name="item-count" type="MappedLevelInt" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="soul" type="xs:int" default="0"/>
        <xs:attribute name="charge" type="xs:int" default="0"/>
    </xs:complexType>

    <xs:complexType name="Channeling">
        <xs:attribute name="skill" type="xs:int" use="required"/>
        <xs:attribute name="mp-consume" type="xs:int" default="0"/>
        <xs:attribute name="initial-delay" type="xs:int" default="0"/>
        <xs:attribute name="interval" type="xs:int" default="2000"/>
    </xs:complexType>

    <xs:complexType name="SkillTarget">
        <xs:sequence>
            <xs:element name="fan-range" type="FanRange" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="type" type="TargetType" default="SELF"/>
        <xs:attribute name="scope" type="AffectScope" default="SINGLE"/>
        <xs:attribute name="object" type="AffectObject" default="ALL"/>
        <xs:attribute name="range" type="xs:int" default="0"/>
        <xs:attribute name="affect-min" type="xs:int" default="-1"/>
        <xs:attribute name="affect-random" type="xs:int" default="0"/>
    </xs:complexType>

    <xs:complexType name="FanRange">
        <xs:attribute name="start-angle" type="xs:int" use="required"/>
        <xs:attribute name="radius" type="xs:int" use="required"/>
        <xs:attribute name="angle" type="xs:int" use="required"/>
    </xs:complexType>

    <xs:complexType name="SkillAttributes">
        <xs:sequence>
            <xs:element name="magic-level" type="MappedLevelInt" minOccurs="0"/>
            <xs:element name="cast-range" type="MappedLevelInt" minOccurs="0"/>
            <xs:element name="reuse" type="MappedLevelInt" minOccurs="0"/>
            <xs:element name="cool-time" type="MappedLevelInt" minOccurs="0"/>
            <xs:element name="effect-point" type="MappedLevelInt" minOccurs="0"/>
            <xs:element name="effect-range" type="MappedLevelInt" minOccurs="0"/>
            <xs:element name="hit-time" type="MappedLevelInt" minOccurs="0"/>
            <xs:element name="activate-rate" type="MappedLevelInt" minOccurs="0"/>
            <xs:element name="element" type="ElementType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="trait" type="TraitType" default="NONE"/>
        <xs:attribute name="next-action" type="ActionType" default="NONE"/>
        <xs:attribute name="property" type="SkillProperty" default="NONE"/>
        <xs:attribute name="static-reuse" type="xs:boolean" default="false"/>
        <xs:attribute name="magic-critical-rate" type="xs:float" default="0"/>
        <xs:attribute name="stay-after-death" type="xs:boolean" default="false"/>
        <xs:attribute name="display-id" type="xs:int"/>
        <xs:attribute name="hit-cancel-time" type="xs:float" default="0"/>
        <xs:attribute name="level-bonus-rate" type="xs:int" default="0"/>
        <xs:attribute name="remove-on-action" type="xs:boolean" default="false"/>
        <xs:attribute name="remove-on-damage" type="xs:boolean" default="false"/>
        <xs:attribute name="blocked-on-olympiad" type="xs:boolean" default="false"/>
        <xs:attribute name="suicide" type="xs:boolean" default="false"/>
        <xs:attribute name="triggered" type="xs:boolean" default="false"/>
        <xs:attribute name="dispellable" type="xs:boolean" default="true"/>
        <xs:attribute name="check" type="xs:boolean" default="true"/>
        <xs:attribute name="without-action" type="xs:boolean" default="false"/>
        <xs:attribute name="cast-disabled" type="xs:boolean" default="false"/>
        <xs:attribute name="no-summon-shared" type="xs:boolean" default="false"/>
        <xs:attribute name="remove-abnormal-on-leave" type="xs:boolean" default="false"/>
        <xs:attribute name="irreplacable" type="xs:boolean" default="false"/>
        <xs:attribute name="block-action-skill" type="xs:boolean" default="false"/>
        <xs:attribute name="auto-use" type="SkillAutoUseType" default="NONE"/>
    </xs:complexType>

    <xs:simpleType name="SkillAutoUseType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="NONE"/>
            <xs:enumeration value="BUFF"/>
            <xs:enumeration value="ACTIVE"/>
            <xs:enumeration value="TRANSFORM"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="ElementType">
        <xs:attribute name="type" type="Element" default="NONE"/>
        <xs:attribute name="value" type="xs:int" default="0"/>
    </xs:complexType>

    <xs:complexType name="Abnormal">
        <xs:sequence>
            <xs:element name="level" type="MappedLevelInt" minOccurs="0"/>
            <xs:element name="time" type="MappedLevelInt"/>
            <xs:element name="chance" type="MappedLevelInt" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="type" type="AbnormalType" default="NONE"/>
        <xs:attribute name="visual" type="AbnormalVisualList"/>
        <xs:attribute name="subordination" type="AbnormalType" default="NONE"/>
        <xs:attribute name="instant" type="xs:boolean" default="false"/>
    </xs:complexType>

    <xs:simpleType name="AbnormalVisualList">
        <xs:list itemType="AbnormalVisualEffect"/>
    </xs:simpleType>

    <xs:simpleType name="AffectScope">
        <xs:restriction base="xs:token">
            <xs:enumeration value="VALAKAS_SCOPE"/>
            <xs:enumeration value="DEAD_PLEDGE"/>
            <xs:enumeration value="DEAD_UNION"/>
            <xs:enumeration value="FAN"/>
            <xs:enumeration value="FAN_PB"/>
            <xs:enumeration value="NONE"/>
            <xs:enumeration value="PARTY"/>
            <xs:enumeration value="DEAD_PARTY"/>
            <xs:enumeration value="PARTY_PLEDGE"/>
            <xs:enumeration value="DEAD_PARTY_PLEDGE"/>
            <xs:enumeration value="PLEDGE"/>
            <xs:enumeration value="POINT_BLANK"/>
            <xs:enumeration value="RANGE"/>
            <xs:enumeration value="RANGE_SORT_BY_HP"/>
            <xs:enumeration value="RING_RANGE"/>
            <xs:enumeration value="SINGLE"/>
            <xs:enumeration value="SQUARE"/>
            <xs:enumeration value="SQUARE_PB"/>
            <xs:enumeration value="STATIC_OBJECT_SCOPE"/>
            <xs:enumeration value="SUMMON_EXCEPT_MASTER"/>
            <xs:enumeration value="WYVERN_SCOPE"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="OperateType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="A1"/>
            <xs:enumeration value="A2"/>
            <xs:enumeration value="A3"/>
            <xs:enumeration value="A4"/>
            <xs:enumeration value="A5"/>
            <xs:enumeration value="A6"/>
            <xs:enumeration value="CA1"/>
            <xs:enumeration value="CA2"/>
            <xs:enumeration value="CA5"/>
            <xs:enumeration value="DA1"/>
            <xs:enumeration value="DA2"/>
            <xs:enumeration value="DA3"/>
            <xs:enumeration value="DA4"/>
            <xs:enumeration value="DA5"/>
            <xs:enumeration value="P"/>
            <xs:enumeration value="T"/>
            <xs:enumeration value="TG"/>
            <xs:enumeration value="AU"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ActionType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="NONE"/>
            <xs:enumeration value="ATTACK"/>
            <xs:enumeration value="CAST"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="SkillProperty">
        <xs:restriction base="xs:token">
            <xs:enumeration value="NONE"/>
            <xs:enumeration value="MAGIC"/>
            <xs:enumeration value="PHYSIC"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TraitType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="NONE"/>
            <xs:enumeration value="SWORD"/>
			<xs:enumeration value="TWO_HAND_SWORD"/>
            <xs:enumeration value="MAGIC_SWORD"/>
            <xs:enumeration value="BLUNT"/>
			<xs:enumeration value="DUAL_BLUNT"/>
            <xs:enumeration value="DAGGER"/>
			<xs:enumeration value="DUAL_DAGGER"/>
            <xs:enumeration value="SPEAR"/>
            <xs:enumeration value="FIST"/>
            <xs:enumeration value="BOW"/>
			<xs:enumeration value="CROSSBOW"/>
			<xs:enumeration value="TWO_HAND_CROSSBOW"/>
            <xs:enumeration value="HAMMER"/>			
			<xs:enumeration value="DUAL"/>
			<xs:enumeration value="DUALFIST"/>
			<xs:enumeration value="ROD"/>
            <xs:enumeration value="STAFF"/>			
			<xs:enumeration value="RAPIER"/>           
            <xs:enumeration value="ANCIENT_SWORD"/>			
            <xs:enumeration value="ETC"/>
            <xs:enumeration value="UNK_8"/>
            <xs:enumeration value="POISON"/>
            <xs:enumeration value="HOLD"/>
            <xs:enumeration value="BLEED"/>
            <xs:enumeration value="SLEEP"/>
            <xs:enumeration value="SHOCK"/>
            <xs:enumeration value="DERANGEMENT"/>
            <xs:enumeration value="BUG_WEAKNESS"/>
            <xs:enumeration value="ANIMAL_WEAKNESS"/>
            <xs:enumeration value="PLANT_WEAKNESS"/>
            <xs:enumeration value="BEAST_WEAKNESS"/>
            <xs:enumeration value="DRAGON_WEAKNESS"/>
            <xs:enumeration value="PARALYZE"/>            
            <xs:enumeration value="BOSS"/>
            <xs:enumeration value="GIANT_WEAKNESS"/>
            <xs:enumeration value="CONSTRUCT_WEAKNESS"/>
            <xs:enumeration value="DEATH"/>
            <xs:enumeration value="VALAKAS"/>
            <xs:enumeration value="ANESTHESIA"/>
            <xs:enumeration value="CRITICAL_POISON"/>
            <xs:enumeration value="ROOT_PHYSICALLY"/>
            <xs:enumeration value="ROOT_MAGICALLY"/>            
            <xs:enumeration value="TURN_STONE"/>
            <xs:enumeration value="GUST"/>
            <xs:enumeration value="PHYSICAL_BLOCKADE"/>
            <xs:enumeration value="TARGET"/>
            <xs:enumeration value="PHYSICAL_WEAKNESS"/>
            <xs:enumeration value="MAGICAL_WEAKNESS"/>           
            <xs:enumeration value="DEMONIC_WEAKNESS"/>
            <xs:enumeration value="DIVINE_WEAKNESS"/>
            <xs:enumeration value="ELEMENTAL_WEAKNESS"/>
            <xs:enumeration value="FAIRY_WEAKNESS"/>
            <xs:enumeration value="HUMAN_WEAKNESS"/>
            <xs:enumeration value="HUMANOID_WEAKNESS"/>
            <xs:enumeration value="UNDEAD_WEAKNESS"/>            
            <xs:enumeration value="KNOCKBACK"/>
            <xs:enumeration value="KNOCKDOWN"/>
            <xs:enumeration value="PULL"/>
            <xs:enumeration value="HATE"/>
            <xs:enumeration value="AGGRESSION"/>
            <xs:enumeration value="AIRBIND"/>
            <xs:enumeration value="DISARM"/>
            <xs:enumeration value="DEPORT"/>
            <xs:enumeration value="CHANGEBODY"/>            
            <xs:enumeration value="ZONE"/>
            <xs:enumeration value="PSYCHIC"/>
            <xs:enumeration value="EMBRYO_WEAKNESS"/>
            <xs:enumeration value="SPIRIT_WEAKNESS"/>           
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="SkillConfig">
        <xs:sequence>
            <xs:element name="time" type="SkillIntProperty" minOccurs="0" maxOccurs="unbounded"/> <!-- skill id and duration in sec -->
            <xs:element name="delay" type="SkillIntProperty" minOccurs="0" maxOccurs="unbounded"/> <!-- skill id and reuse in sec -->
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="SkillIntProperty">
        <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="value" type="xs:int" use="required"/>
    </xs:complexType>
</xs:schema>

=== L2jOrg/Datapack/data/skills/60300-60399.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org skills.xsd">
    <skill id="60300" name="P. Evasion: 100 - Healing 30%">
        <!-- P. Evasion: 100 - Healing 30%% -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60301" name="Equipped Shield - Atk. Spd. +100%">
        <!-- Equipped Shield - Atk. Spd.: +100%% -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60302" name="Equipped Shield - Atk. Spd. +100">
        <!-- Equipped Shield - Atk. Spd. +100 -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60303" name="Atk. Spd.: 100% - Healing 60%">
        <!-- Atk. Spd.: 100%% - Healing 60%% -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60304" name="Atk. Spd.: 100 - Healing 60%">
        <!-- Atk. Spd.: 100 - Healing 60%% -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60305" name="Atk. Spd.: 100% - Healing 30%">
        <!-- Atk. Spd.: 100%% - Healing 30%% -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60306" name="Atk. Spd.: 100 - Healing 30%">
        <!-- Atk. Spd.: 100 - Healing 30%% -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60307" name="Speed: 100 - Out of combat">
        <!-- Speed: 100 - Out of combat -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60308" name="P. Atk.: Increase due to the level">
        <!-- P. Atk.: Increase due to the level -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60309" name="M. Atk.: Increase due to the level">
        <!-- M. Atk.: Increase due to the level -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60310" name="P. Def.: Increase due to the level">
        <!-- P. Def.: Increase due to the level -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60311" name="M. Def.: Increase due to the level">
        <!-- M. Def.: Increase due to the level -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60312" name="P. Accuracy: Increase due to the level">
        <!-- P. Accuracy: Increase due to the level -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60313" name="M. Accuracy: Increase due to the level">
        <!-- M. Accuracy: Increase due to the level -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60314" name="P. Evasion: Increase due to the level">
        <!-- P. Evasion: Increase due to the level -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60315" name="M. Evasion: Increase due to the level">
        <!-- M. Evasion: Increase due to the level -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60316" name="Atk. Spd.: Increase due to the level">
        <!-- Atk. Spd.: Increase due to the level -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60317" name="Casting Spd.: Increase due to the level">
        <!-- Casting Spd.: Increase due to the level -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60318" name="P. Accuracy: Heavy Armor - 100%">
        <!-- P. Accuracy: Heavy Armor - 100%% -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60319" name="P. Accuracy: Heavy Armor - 100">
        <!-- P. Accuracy: Heavy Armor - 100 -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60320" name="P. Accuracy: Light Armor - 100%">
        <!-- P. Accuracy: Light Armor - 100%% -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60321" name="P. Accuracy: Light Armor - 100">
        <!-- P. Accuracy: Light Armor - 100 -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60322" name="P. Accuracy: Robe - 100%">
        <!-- P. Accuracy: Robe - 100%% -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60323" name="P. Accuracy: Robe - 100">
        <!-- P. Accuracy: Robe - 100 -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60324" name="P. Accuracy: All - 100%">
        <!-- P. Accuracy: All - 100%% -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60325" name="P. Accuracy: All - 100">
        <!-- P. Accuracy: All - 100 -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60326" name="Speed: Increase due to the level">
        <!-- Speed: Increase due to the level -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60327" name="M. Accuracy: 100%">
        <!-- M. Accuracy: 100%% -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60328" name="M. Accuracy: +100">
        <!-- M. Accuracy: +100 -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60329" name="M. Evasion: 100%">
        <!-- M. Evasion: 100%% -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60330" name="M. Evasion: 100">
        <!-- M. Evasion: 100 -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60331" name="Casting Spd. - Bow: 100%">
        <!-- Casting Spd. - Bow: 100%% -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="60332" name="Casting Spd. - Bow: 100">
        <!-- Casting Spd. - Bow: 100 -->
        <icon initial="iccon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
</list>

=== L2jOrg/Datapack/data/skills/07100-07199.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org skills.xsd">
    <skill id="7122" name="Raid Boss (Lv. 80)">
        <!-- Enchanted by Shillien, enshrouded in darkness, Antharas' minion is guarding the lands near the Ant Nest. -->
        <icon initial="icon.skillraid"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="7123" name="Raid Boss (Lv. 80)">
        <!-- Enchanted by Shillien, enshrouded in darkness, Giran is guarding the lands and praying about resurrection. -->
        <icon initial="icon.skillraid"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="7124" name="Raid Boss (Lv. 80)">
        <!-- Enchanted by Shillien, enshrouded in darkness, minion of Core is guarding the lands around Cruma Tower. -->
        <icon initial="icon.skillraid"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="7125" name="Raid Boss (Lv. 80)">
        <!-- Enchanted by Shillien, enshrouded in darkness, minion of Orfen is guarding the Plains of the Lizardmen. -->
        <icon initial="icon.skillraid"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="7126" name="Master's Blessing - Holy Weapon" max-level="3" action="A1">
        <!-- 
			level 1: The GM is always by your side. For 1 h., party members' Holy Attack +20.
			level 2: The GM is always by your side. For 4 h., party members' Holy Attack +20.
			level 3: The GM is always by your side. For 8 h., party members' Holy Attack +20.
		-->
        <icon initial="icon.skill1043"/>
        <attributes>
            <cast-range initial="900"/>
            <reuse initial="1000"/>
            <effect-point initial="243"/>
            <hit-time initial="500"/>
        </attributes>
        <target/>
    </skill>
    <skill id="7127" name="Master's Blessing - Stun Resistance" max-level="3" action="A1">
        <!-- 
			level 1: The GM is always by your side. For 1 h., Stun Resistance +40%%.
			level 2: The GM is always by your side. For 4 h., Stun Resistance +40%%.
			level 3: The GM is always by your side. For 8 h., Stun Resistance +40%%.
		-->
        <icon initial="icon.skill1259"/>
        <attributes>
            <cast-range initial="900"/>
            <reuse initial="1000"/>
            <effect-point initial="646"/>
            <hit-time initial="500"/>
        </attributes>
        <target/>
    </skill>
    <skill id="7129" name="Triple Sonic Slash" max-level="4" action="A1">
        <!--  -->
        <icon initial="icon.skill0000"/>
        <attributes>
            <cast-range initial="40"/>
            <reuse initial="30000"/>
            <effect-point initial="-100"/>
            <hit-time initial="1800"/>
        </attributes>
        <consume>
            <mana initial="159">
                <value level="2">165</value>
                <value level="3">168</value>
                <value level="4">170</value>
            </mana>
        </consume>
        <target/>
    </skill>
    <skill id="7130" name="Sonic Blaster" max-level="4" action="A1">
        <!--  -->
        <icon initial="icon.skill0000"/>
        <attributes>
            <cast-range initial="600"/>
            <reuse initial="15000"/>
            <effect-point initial="-100"/>
            <hit-time initial="1900"/>
        </attributes>
        <consume>
            <mana initial="80">
                <value level="2">83</value>
                <value level="3">84</value>
                <value level="4">85</value>
            </mana>
        </consume>
        <target/>
    </skill>
</list>
