=== L2jOrg/Datapack/data/skills/skills.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://l2j.org"
           xmlns="http://l2j.org"
           elementFormDefault="qualified">

    <xs:include schemaLocation="../xsd/common.xsd"/>
    <xs:include schemaLocation="conditions.xsd"/>
    <xs:include schemaLocation="effects.xsd"/>

    <xs:element name="list">
        <xs:complexType>
            <xs:choice>
                <xs:element name="skill-config" type="SkillConfig"/>
                <xs:element name="skill" type="Skill" maxOccurs="unbounded" minOccurs="0"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Skill">
        <xs:sequence>
            <xs:element name="icon" type="MappedLevelToken"/>
            <xs:element name="attributes" type="SkillAttributes"/>
            <xs:element name="consume" type="Consume" minOccurs="0"/>
            <xs:element name="target" type="SkillTarget"/>
            <xs:element name="abnormal" type="Abnormal" minOccurs="0"/>
            <xs:element name="resist-abnormals" type="AbnormalTypeList" minOccurs="0"/>
            <xs:element name="channeling" type="Channeling" minOccurs="0"/>
            <xs:element name="conditions" type="Conditions" minOccurs="0"/>
            <xs:element name="effects" type="Effects" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="max-level" type="xs:positiveInteger" default="1"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="debuff" type="xs:boolean" default="false"/>
        <xs:attribute name="action" type="OperateType" default="P"/>
        <xs:attribute name="type" type="SkillType" default="PHYSIC"/>
    </xs:complexType>

    <xs:complexType name="Consume">
        <xs:sequence>
            <xs:element name="mana-init" type="MappedLevelInt" minOccurs="0"/>
            <xs:element name="mana" type="MappedLevelInt" minOccurs="0"/>
            <xs:element name="hp" type="MappedLevelInt" minOccurs="0"/>
            <xs:element name="item" type="MappedLevelInt" minOccurs="0"/>
            <xs:element name="item-count" type="MappedLevelInt" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="soul" type="xs:int" default="0"/>
        <xs:attribute name="charge" type="xs:int" default="0"/>
    </xs:complexType>

    <xs:complexType name="Channeling">
        <xs:attribute name="skill" type="xs:int" use="required"/>
        <xs:attribute name="mp-consume" type="xs:int" default="0"/>
        <xs:attribute name="initial-delay" type="xs:int" default="0"/>
        <xs:attribute name="interval" type="xs:int" default="2000"/>
    </xs:complexType>

    <xs:complexType name="SkillTarget">
        <xs:sequence>
            <xs:element name="fan-range" type="FanRange" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="type" type="TargetType" default="SELF"/>
        <xs:attribute name="scope" type="AffectScope" default="SINGLE"/>
        <xs:attribute name="object" type="AffectObject" default="ALL"/>
        <xs:attribute name="range" type="xs:int" default="0"/>
        <xs:attribute name="affect-min" type="xs:int" default="-1"/>
        <xs:attribute name="affect-random" type="xs:int" default="0"/>
    </xs:complexType>

    <xs:complexType name="FanRange">
        <xs:attribute name="start-angle" type="xs:int" use="required"/>
        <xs:attribute name="radius" type="xs:int" use="required"/>
        <xs:attribute name="angle" type="xs:int" use="required"/>
    </xs:complexType>

    <xs:complexType name="SkillAttributes">
        <xs:sequence>
            <xs:element name="magic-level" type="MappedLevelInt" minOccurs="0"/>
            <xs:element name="cast-range" type="MappedLevelInt" minOccurs="0"/>
            <xs:element name="reuse" type="MappedLevelInt" minOccurs="0"/>
            <xs:element name="cool-time" type="MappedLevelInt" minOccurs="0"/>
            <xs:element name="effect-point" type="MappedLevelInt" minOccurs="0"/>
            <xs:element name="effect-range" type="MappedLevelInt" minOccurs="0"/>
            <xs:element name="hit-time" type="MappedLevelInt" minOccurs="0"/>
            <xs:element name="activate-rate" type="MappedLevelInt" minOccurs="0"/>
            <xs:element name="element" type="ElementType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="trait" type="TraitType" default="NONE"/>
        <xs:attribute name="next-action" type="ActionType" default="NONE"/>
        <xs:attribute name="property" type="SkillProperty" default="NONE"/>
        <xs:attribute name="static-reuse" type="xs:boolean" default="false"/>
        <xs:attribute name="magic-critical-rate" type="xs:float" default="0"/>
        <xs:attribute name="stay-after-death" type="xs:boolean" default="false"/>
        <xs:attribute name="display-id" type="xs:int"/>
        <xs:attribute name="hit-cancel-time" type="xs:float" default="0"/>
        <xs:attribute name="level-bonus-rate" type="xs:int" default="0"/>
        <xs:attribute name="remove-on-action" type="xs:boolean" default="false"/>
        <xs:attribute name="remove-on-damage" type="xs:boolean" default="false"/>
        <xs:attribute name="blocked-on-olympiad" type="xs:boolean" default="false"/>
        <xs:attribute name="suicide" type="xs:boolean" default="false"/>
        <xs:attribute name="triggered" type="xs:boolean" default="false"/>
        <xs:attribute name="dispellable" type="xs:boolean" default="true"/>
        <xs:attribute name="check" type="xs:boolean" default="true"/>
        <xs:attribute name="without-action" type="xs:boolean" default="false"/>
        <xs:attribute name="cast-disabled" type="xs:boolean" default="false"/>
        <xs:attribute name="no-summon-shared" type="xs:boolean" default="false"/>
        <xs:attribute name="remove-abnormal-on-leave" type="xs:boolean" default="false"/>
        <xs:attribute name="irreplacable" type="xs:boolean" default="false"/>
        <xs:attribute name="block-action-skill" type="xs:boolean" default="false"/>
        <xs:attribute name="auto-use" type="SkillAutoUseType" default="NONE"/>
    </xs:complexType>

    <xs:simpleType name="SkillAutoUseType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="NONE"/>
            <xs:enumeration value="BUFF"/>
            <xs:enumeration value="ACTIVE"/>
            <xs:enumeration value="TRANSFORM"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="ElementType">
        <xs:attribute name="type" type="Element" default="NONE"/>
        <xs:attribute name="value" type="xs:int" default="0"/>
    </xs:complexType>

    <xs:complexType name="Abnormal">
        <xs:sequence>
            <xs:element name="level" type="MappedLevelInt" minOccurs="0"/>
            <xs:element name="time" type="MappedLevelInt"/>
            <xs:element name="chance" type="MappedLevelInt" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="type" type="AbnormalType" default="NONE"/>
        <xs:attribute name="visual" type="AbnormalVisualList"/>
        <xs:attribute name="subordination" type="AbnormalType" default="NONE"/>
        <xs:attribute name="instant" type="xs:boolean" default="false"/>
    </xs:complexType>

    <xs:simpleType name="AbnormalVisualList">
        <xs:list itemType="AbnormalVisualEffect"/>
    </xs:simpleType>

    <xs:simpleType name="AffectScope">
        <xs:restriction base="xs:token">
            <xs:enumeration value="VALAKAS_SCOPE"/>
            <xs:enumeration value="DEAD_PLEDGE"/>
            <xs:enumeration value="DEAD_UNION"/>
            <xs:enumeration value="FAN"/>
            <xs:enumeration value="FAN_PB"/>
            <xs:enumeration value="NONE"/>
            <xs:enumeration value="PARTY"/>
            <xs:enumeration value="DEAD_PARTY"/>
            <xs:enumeration value="PARTY_PLEDGE"/>
            <xs:enumeration value="DEAD_PARTY_PLEDGE"/>
            <xs:enumeration value="PLEDGE"/>
            <xs:enumeration value="POINT_BLANK"/>
            <xs:enumeration value="RANGE"/>
            <xs:enumeration value="RANGE_SORT_BY_HP"/>
            <xs:enumeration value="RING_RANGE"/>
            <xs:enumeration value="SINGLE"/>
            <xs:enumeration value="SQUARE"/>
            <xs:enumeration value="SQUARE_PB"/>
            <xs:enumeration value="STATIC_OBJECT_SCOPE"/>
            <xs:enumeration value="SUMMON_EXCEPT_MASTER"/>
            <xs:enumeration value="WYVERN_SCOPE"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="OperateType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="A1"/>
            <xs:enumeration value="A2"/>
            <xs:enumeration value="A3"/>
            <xs:enumeration value="A4"/>
            <xs:enumeration value="A5"/>
            <xs:enumeration value="A6"/>
            <xs:enumeration value="CA1"/>
            <xs:enumeration value="CA2"/>
            <xs:enumeration value="CA5"/>
            <xs:enumeration value="DA1"/>
            <xs:enumeration value="DA2"/>
            <xs:enumeration value="DA3"/>
            <xs:enumeration value="DA4"/>
            <xs:enumeration value="DA5"/>
            <xs:enumeration value="P"/>
            <xs:enumeration value="T"/>
            <xs:enumeration value="TG"/>
            <xs:enumeration value="AU"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ActionType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="NONE"/>
            <xs:enumeration value="ATTACK"/>
            <xs:enumeration value="CAST"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="SkillProperty">
        <xs:restriction base="xs:token">
            <xs:enumeration value="NONE"/>
            <xs:enumeration value="MAGIC"/>
            <xs:enumeration value="PHYSIC"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TraitType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="NONE"/>
            <xs:enumeration value="SWORD"/>
			<xs:enumeration value="TWO_HAND_SWORD"/>
            <xs:enumeration value="MAGIC_SWORD"/>
            <xs:enumeration value="BLUNT"/>
			<xs:enumeration value="DUAL_BLUNT"/>
            <xs:enumeration value="DAGGER"/>
			<xs:enumeration value="DUAL_DAGGER"/>
            <xs:enumeration value="SPEAR"/>
            <xs:enumeration value="FIST"/>
            <xs:enumeration value="BOW"/>
			<xs:enumeration value="CROSSBOW"/>
			<xs:enumeration value="TWO_HAND_CROSSBOW"/>
            <xs:enumeration value="HAMMER"/>			
			<xs:enumeration value="DUAL"/>
			<xs:enumeration value="DUALFIST"/>
			<xs:enumeration value="ROD"/>
            <xs:enumeration value="STAFF"/>			
			<xs:enumeration value="RAPIER"/>           
            <xs:enumeration value="ANCIENT_SWORD"/>			
            <xs:enumeration value="ETC"/>
            <xs:enumeration value="UNK_8"/>
            <xs:enumeration value="POISON"/>
            <xs:enumeration value="HOLD"/>
            <xs:enumeration value="BLEED"/>
            <xs:enumeration value="SLEEP"/>
            <xs:enumeration value="SHOCK"/>
            <xs:enumeration value="DERANGEMENT"/>
            <xs:enumeration value="BUG_WEAKNESS"/>
            <xs:enumeration value="ANIMAL_WEAKNESS"/>
            <xs:enumeration value="PLANT_WEAKNESS"/>
            <xs:enumeration value="BEAST_WEAKNESS"/>
            <xs:enumeration value="DRAGON_WEAKNESS"/>
            <xs:enumeration value="PARALYZE"/>            
            <xs:enumeration value="BOSS"/>
            <xs:enumeration value="GIANT_WEAKNESS"/>
            <xs:enumeration value="CONSTRUCT_WEAKNESS"/>
            <xs:enumeration value="DEATH"/>
            <xs:enumeration value="VALAKAS"/>
            <xs:enumeration value="ANESTHESIA"/>
            <xs:enumeration value="CRITICAL_POISON"/>
            <xs:enumeration value="ROOT_PHYSICALLY"/>
            <xs:enumeration value="ROOT_MAGICALLY"/>            
            <xs:enumeration value="TURN_STONE"/>
            <xs:enumeration value="GUST"/>
            <xs:enumeration value="PHYSICAL_BLOCKADE"/>
            <xs:enumeration value="TARGET"/>
            <xs:enumeration value="PHYSICAL_WEAKNESS"/>
            <xs:enumeration value="MAGICAL_WEAKNESS"/>           
            <xs:enumeration value="DEMONIC_WEAKNESS"/>
            <xs:enumeration value="DIVINE_WEAKNESS"/>
            <xs:enumeration value="ELEMENTAL_WEAKNESS"/>
            <xs:enumeration value="FAIRY_WEAKNESS"/>
            <xs:enumeration value="HUMAN_WEAKNESS"/>
            <xs:enumeration value="HUMANOID_WEAKNESS"/>
            <xs:enumeration value="UNDEAD_WEAKNESS"/>            
            <xs:enumeration value="KNOCKBACK"/>
            <xs:enumeration value="KNOCKDOWN"/>
            <xs:enumeration value="PULL"/>
            <xs:enumeration value="HATE"/>
            <xs:enumeration value="AGGRESSION"/>
            <xs:enumeration value="AIRBIND"/>
            <xs:enumeration value="DISARM"/>
            <xs:enumeration value="DEPORT"/>
            <xs:enumeration value="CHANGEBODY"/>            
            <xs:enumeration value="ZONE"/>
            <xs:enumeration value="PSYCHIC"/>
            <xs:enumeration value="EMBRYO_WEAKNESS"/>
            <xs:enumeration value="SPIRIT_WEAKNESS"/>           
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="SkillConfig">
        <xs:sequence>
            <xs:element name="time" type="SkillIntProperty" minOccurs="0" maxOccurs="unbounded"/> <!-- skill id and duration in sec -->
            <xs:element name="delay" type="SkillIntProperty" minOccurs="0" maxOccurs="unbounded"/> <!-- skill id and reuse in sec -->
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="SkillIntProperty">
        <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="value" type="xs:int" use="required"/>
    </xs:complexType>
</xs:schema>

=== L2jOrg/Datapack/data/skills/17600-17699.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org skills.xsd">
    <skill id="17608" name="Energy of Delusion" action="A2">
        <!-- Fishing place, filled with Fantastical Energy. -->
        <icon initial="icon.etc_dragons_blood_i03"/>
        <attributes>
            <cast-range initial="-1"/>
        </attributes>
        <target/>
    </skill>
    <skill id="17613" name="Summon Agathion Aries" action="A1">
        <!-- Summons an agathion. -->
        <icon initial="icon.etc_summon_aga_agit_i00"/>
        <attributes>
            <magic-level initial="85"/>
            <cast-range initial="-1"/>
            <hit-time initial="3000"/>
        </attributes>
        <target/>
        <effects>
            <summon-agathion id="13411"/>
        </effects>
    </skill>
    <skill id="17619" name="Summon Agathion Pisces" action="A1">
        <!-- Summons an agathion. -->
        <icon initial="icon.etc_summon_aga_agit_i00"/>
        <attributes>
            <magic-level initial="85"/>
            <cast-range initial="-1"/>
            <hit-time initial="3000"/>
        </attributes>
        <target/>
        <effects>
            <summon-agathion id="13407"/>
        </effects>
    </skill>
    <skill id="17621" name="Summon Agathion Cancer" action="A1">
        <!-- Summons an agathion. -->
        <icon initial="icon.etc_summon_aga_agit_i00"/>
        <attributes>
            <magic-level initial="85"/>
            <cast-range initial="-1"/>
            <hit-time initial="3000"/>
        </attributes>
        <target/>
        <effects>
            <summon-agathion id="13409"/>
        </effects>
    </skill>
    <skill id="17625" name="Agathion Cute Trick - Aries" action="A1">
        <!-- Makes an agathion perform a cute trick. -->
        <icon initial="icon.skill_agathion_cute"/>
        <attributes>
            <cast-range initial="-1"/>
            <hit-time initial="3000"/>
        </attributes>
        <target/>
    </skill>
    <skill id="17685" name="Uldie's Gift" action="A1">
        <!--  -->
        <icon initial="icon.skill0000"/>
        <attributes>
            <cast-range initial="-1"/>
            <effect-point initial="1"/>
        </attributes>
        <target/>
    </skill>
    <skill id="17686" name="Uldie's Energy" max-level="2" action="A2">
        <!-- 
			level 1: Buff from Uldie. For 2 h., Acquired XP/ SP +10%, P./ M. Atk. +5%, Atk. Spd./ Casting Spd. +5%. A chance to obtain Uldie's Elite Gift when the buff is cancelled.  Note! The gift can't be obtained if your character is dead or if there is no space in your inventory.
			level 2: Buff from Uldie.
		-->
        <icon initial="BranchSys.icon.br_sevenlove_girlpresent_i00"/>
        <attributes>
            <cast-range initial="900">
                <value level="2">-1</value>
            </cast-range>
            <effect-point initial="1"/>
        </attributes>
        <target/>
    </skill>
    <skill id="17689" name="Uldie's Valuable Gift" action="A1">
        <!-- none -->
        <icon initial="icon.skill0000"/>
        <attributes>
            <cast-range initial="-1"/>
        </attributes>
        <target/>
    </skill>
    <skill id="17695" name="Squash Seed" action="A1">
        <!-- Skill for summoning a Pumpkin for an anniversary. -->
        <icon initial="icon.skill17695"/>
        <attributes>
            <cast-range initial="-1"/>
            <reuse initial="5000"/>
            <cool-time initial="500"/>
            <hit-time initial="1000"/>
        </attributes>
        <target/>
    </skill>
    <skill id="17696" name="Cloned Large Squash Seed" action="A1">
        <!-- Skill for summoning a Pumpkin for an anniversary. -->
        <icon initial="icon.skill17696"/>
        <attributes>
            <cast-range initial="-1"/>
            <reuse initial="5000"/>
            <cool-time initial="500"/>
            <hit-time initial="1000"/>
        </attributes>
        <target/>
    </skill>
</list>

=== L2jOrg/Datapack/data/skills/14800-14899.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org skills.xsd">
    <skill id="14826" name="Intense Slash" max-level="9" action="A1">
        <!-- 
			level 1: Concentrates the spirit energy to deal physical damage to the target. Power 831.
			level 2: Concentrates the spirit energy to deal physical damage to the target. Power 8287.
			level 3: Concentrates the spirit energy to deal physical damage to the target. Power 400.
			level 4: Concentrates the spirit energy to deal physical damage to the target. Power 831.
			level 5: Concentrates the spirit energy to deal physical damage to the target. Power 1532.
			level 6: Concentrates the spirit energy to deal physical damage to the target. Power 2575.
			level 7: Concentrates the spirit energy to deal physical damage to the target. Power 4430.
			level 8: Concentrates the spirit energy to deal physical damage to the target. Power 6656.
			level 9: Concentrates the spirit energy to deal physical damage to the target. Power 8287.
		-->
        <icon initial="icon.skill_transform_s_attack"/>
        <attributes magic-critical-rate="-5.0">
            <cast-range initial="-1"/>
            <reuse initial="5000"/>
            <cool-time initial="500"/>
            <effect-point initial="-183"/>
            <hit-time initial="2500"/>
        </attributes>
        <target affect-min="6" affect-random="12" object="NOT_FRIEND" range="150" scope="RANGE" type="ENEMY"/>
        <effects>
            <physical-attack>
                <power initial="831.0">
                    <value level="2">8287.0</value>
                    <value level="3">400.0</value>
                    <value level="4">831.0</value>
                    <value level="5">1532.0</value>
                    <value level="6">2575.0</value>
                    <value level="7">4430.0</value>
                    <value level="8">6656.0</value>
                    <value level="9">8287.0</value>
                </power>
            </physical-attack>
        </effects>
    </skill>
    <skill id="14828" name="Purity Blast" max-level="9" action="A1" type="MAGIC">
        <!-- 
			level 1: Inflicts damage on nearby enemies with 50 Power added to M. Atk. using the power of holy magic.
			level 2: Inflicts damage on nearby enemies with 120 Power added to M. Atk. using the power of holy magic.
			level 3: Inflicts damage on nearby enemies with 39 Power added to M. Atk. using the power of holy magic.
			level 4: Inflicts damage on nearby enemies with 50 Power added to M. Atk. using the power of holy magic.
			level 5: Inflicts damage on nearby enemies with 66 Power added to M. Atk. using the power of holy magic.
			level 6: Inflicts damage on nearby enemies with 82 Power added to M. Atk. using the power of holy magic.
			level 7: Inflicts damage on nearby enemies with 94 Power added to M. Atk. using the power of holy magic.
			level 8: Inflicts damage on nearby enemies with 108 Power added to M. Atk. using the power of holy magic.
			level 9: Inflicts damage on nearby enemies with 120 Power added to M. Atk. using the power of holy magic.
		-->
        <icon initial="icon.skill_transform_s_attack"/>
        <attributes magic-critical-rate="-5.0">
            <cast-range initial="500"/>
            <reuse initial="7000"/>
            <cool-time initial="500"/>
            <effect-point initial="-183"/>
            <effect-range initial="1000"/>
            <hit-time initial="2500"/>
        </attributes>
        <target affect-min="5" affect-random="12" object="NOT_FRIEND" range="200" scope="RANGE" type="ENEMY"/>
        <effects>
            <magical-attack>
                <power initial="50.0">
                    <value level="2">120.0</value>
                    <value level="3">39.0</value>
                    <value level="4">50.0</value>
                    <value level="5">66.0</value>
                    <value level="6">82.0</value>
                    <value level="7">94.0</value>
                    <value level="8">108.0</value>
                    <value level="9">120.0</value>
                </power>
            </magical-attack>
        </effects>
    </skill>
    <skill id="14830" name="Gray Explosion" max-level="9" action="A1">
        <!-- 
			level 1: Deals damage to the target with 985 Power using the power of a devout heart.
			level 2: Deals damage to the target with 9861 Power using the power of a devout heart.
			level 3: Deals damage to the target with 473 Power using the power of a devout heart.
			level 4: Deals damage to the target with 985 Power using the power of a devout heart.
			level 5: Deals damage to the target with 1814 Power using the power of a devout heart.
			level 6: Deals damage to the target with 3048 Power using the power of a devout heart.
			level 7: Deals damage to the target with 5269 Power using the power of a devout heart.
			level 8: Deals damage to the target with 7904 Power using the power of a devout heart.
			level 9: Deals damage to the target with 9861 Power using the power of a devout heart.
		-->
        <icon initial="icon.skill_transform_s_attack"/>
        <attributes magic-critical-rate="-5.0">
            <cast-range initial="-1"/>
            <reuse initial="5000"/>
            <cool-time initial="500"/>
            <effect-point initial="-183"/>
            <hit-time initial="2500"/>
        </attributes>
        <target affect-min="6" affect-random="12" object="NOT_FRIEND" range="150" scope="RANGE" type="ENEMY"/>
        <effects>
            <physical-attack>
                <power initial="985.0">
                    <value level="2">9861.0</value>
                    <value level="3">473.0</value>
                    <value level="4">985.0</value>
                    <value level="5">1814.0</value>
                    <value level="6">3048.0</value>
                    <value level="7">5269.0</value>
                    <value level="8">7904.0</value>
                    <value level="9">9861.0</value>
                </power>
            </physical-attack>
        </effects>
    </skill>
    <skill id="14832" name="Platonic Tempest" max-level="9" action="A1" type="MAGIC">
        <!-- 
			level 1: Inflicts magical damage on nearby enemies with 55 Power added to M. Atk. by fully concentrating on holy magic.
			level 2: Inflicts magical damage on nearby enemies with 133 Power added to M. Atk. by fully concentrating on holy magic.
			level 3: Inflicts magical damage on nearby enemies with 43 Power added to M. Atk. by fully concentrating on holy magic.
			level 4: Inflicts magical damage on nearby enemies with 55 Power added to M. Atk. by fully concentrating on holy magic.
			level 5: Inflicts magical damage on nearby enemies with 72 Power added to M. Atk. by fully concentrating on holy magic.
			level 6: Inflicts magical damage on nearby enemies with 91 Power added to M. Atk. by fully concentrating on holy magic.
			level 7: Inflicts magical damage on nearby enemies with 104 Power added to M. Atk. by fully concentrating on holy magic.
			level 8: Inflicts magical damage on nearby enemies with 120 Power added to M. Atk. by fully concentrating on holy magic.
			level 9: Inflicts magical damage on nearby enemies with 133 Power added to M. Atk. by fully concentrating on holy magic.
		-->
        <icon initial="icon.skill_transform_s_attack"/>
        <attributes magic-critical-rate="-5.0">
            <magic-level initial="40">
                <value level="2">85</value>
                <value level="3">30</value>
                <value level="4">40</value>
                <value level="5">50</value>
                <value level="6">60</value>
                <value level="7">70</value>
                <value level="8">80</value>
                <value level="9">85</value>
            </magic-level>
            <cast-range initial="500"/>
            <reuse initial="7000"/>
            <cool-time initial="500"/>
            <effect-point initial="-183"/>
            <effect-range initial="1000"/>
            <hit-time initial="2500"/>
        </attributes>
        <target affect-min="5" affect-random="12" object="NOT_FRIEND" range="200" scope="RANGE" type="ENEMY"/>
        <effects>
            <magical-attack>
                <power initial="55.0">
                    <value level="2">133.0</value>
                    <value level="3">43.0</value>
                    <value level="4">55.0</value>
                    <value level="5">72.0</value>
                    <value level="6">91.0</value>
                    <value level="7">104.0</value>
                    <value level="8">120.0</value>
                    <value level="9">133.0</value>
                </power>
            </magical-attack>
        </effects>
    </skill>
</list>

=== L2jOrg/Datapack/data/skills/49100-49199.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org skills.xsd">
    <skill id="49100" name="Pet HP Recovery Potion">
        <!--  -->
        <icon initial="icon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="49101" name="1st Pet Evolution">
        <!--  -->
        <icon initial="icon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
    <skill id="49102" name="2nd Pet Evolution">
        <!--  -->
        <icon initial="icon.skill0000"/>
        <attributes/>
        <target/>
    </skill>
</list>
