=== L2jOrg/Datapack/data/zones/zones.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="http://l2j.org"
		   xmlns="http://l2j.org"
		   elementFormDefault="qualified">

	<xs:include schemaLocation="../xsd/common.xsd"/>
	<xs:include schemaLocation="zone-types.xsd"/>

	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="abstractZone" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="enabled" type="xs:boolean" default="true" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="form" type="ZoneForm"/>
	<xs:element name="cube" type="Cube" substitutionGroup="form"/>
	<xs:element name="cylinder" type="Cylinder" substitutionGroup="form"/>
	<xs:element name="polygon" type="Polygon" substitutionGroup="form"/>

	<xs:element name="abstractZone" type="AbstractZone" abstract="true"/>
	<xs:element name="castle" type="CastleZone" substitutionGroup="abstractZone"/>
	<xs:element name="clan-hall" type="ClanHallZone" substitutionGroup="abstractZone"/>
	<xs:element name="condition" type="ConditionZone" substitutionGroup="abstractZone"/>
	<xs:element name="damage" type="DamageZone" substitutionGroup="abstractZone"/>
	<xs:element name="effect" type="EffectZone" substitutionGroup="abstractZone"/>
	<xs:element name="fishing" type="FishingZone" substitutionGroup="abstractZone"/>
	<xs:element name="fort" type="FortZone" substitutionGroup="abstractZone"/>
	<xs:element name="jail" type="JailZone" substitutionGroup="abstractZone"/>
	<xs:element name="mother-tree" type="MotherTreeZone" substitutionGroup="abstractZone"/>
	<xs:element name="no-landing" type="NoLandingZone" substitutionGroup="abstractZone"/>
	<xs:element name="no-restart" type="NoRestartZone" substitutionGroup="abstractZone"/>
	<xs:element name="olympiad-stadium" type="OlympiadStadiumZone" substitutionGroup="abstractZone"/>
	<xs:element name="peace" type="PeaceZone" substitutionGroup="abstractZone"/>
	<xs:element name="residence-teleport" type="ResidenceTeleportZone" substitutionGroup="abstractZone"/>
	<xs:element name="respawn" type="RespawnZone" substitutionGroup="abstractZone"/>
	<xs:element name="script-zone" type="ScriptZone" substitutionGroup="abstractZone"/>
	<xs:element name="siege" type="SiegeZone" substitutionGroup="abstractZone"/>
	<xs:element name="swamp" type="SwampZone" substitutionGroup="abstractZone"/>
	<xs:element name="tax" type="TaxZone" substitutionGroup="abstractZone"/>
	<xs:element name="water" type="WaterZone" substitutionGroup="abstractZone"/>
	<xs:element name="zone" type="Zone" substitutionGroup="abstractZone"/>

	<xs:element name="territory" type="Territory" substitutionGroup="abstractZone"/>

	<xs:complexType name="Territory">
		<xs:complexContent>
			<xs:extension base="AbstractZone"/>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="FishingZone">
		<xs:complexContent>
			<xs:extension base="AbstractZone"/>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="JailZone">
		<xs:complexContent>
			<xs:extension base="AbstractZone"/>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="RespawnZone">
		<xs:complexContent>
			<xs:extension base="AbstractZone">
				<xs:sequence>
					<xs:element name="respawn" type="Respawn" maxOccurs="unbounded" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="ScriptZone">
		<xs:complexContent>
			<xs:extension base="AbstractZone">
				<xs:sequence>
					<xs:element name="attributes" type="ZoneAttributes"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="WaterZone">
		<xs:complexContent>
			<xs:extension base="AbstractZone"/>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="CastleZone">
		<xs:complexContent>
			<xs:extension base="AbstractZone">
				<xs:sequence>
					<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="castle-id" type="xs:int"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="ClanHallZone">
		<xs:complexContent>
			<xs:extension base="AbstractZone">
				<xs:attribute name="hall-id" type="xs:int" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="ConditionZone">
		<xs:complexContent>
			<xs:extension base="AbstractZone">
				<xs:attribute name="allow-bookmark" type="xs:boolean" default="true"/>
				<xs:attribute name="allow-drop" type="xs:boolean" default="true"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="DamageZone">
		<xs:complexContent>
			<xs:extension base="AbstractZone">
				<xs:sequence>
					<xs:element name="attributes" type="DamageAttributes"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="DamageAttributes">
		<xs:complexContent>
			<xs:extension base="ZoneAttributes">
				<xs:attribute name="hp" type="xs:int" default="0"/>
				<xs:attribute name="mp" type="xs:int" default="0"/>
				<xs:attribute name="castle-id" type="xs:int" default="0"/>
				<xs:attribute name="start-time" type="xs:int" default="10"/>
				<xs:attribute name="delay" type="xs:int" default="5000"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="EffectZone">
		<xs:complexContent>
			<xs:extension base="AbstractZone">
				<xs:sequence>
					<xs:element name="attributes" type="EffectAttributes"/>
					<xs:element name="skill" type="SkillInfo" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="EffectAttributes">
		<xs:complexContent>
			<xs:extension base="ZoneAttributes">
				<xs:attribute name="chance" type="xs:float" default="100"/>
				<xs:attribute name="bypass-conditions" type="xs:boolean" default="false"/>
				<xs:attribute name="show-danger-icon" type="xs:boolean" default="true"/>
				<xs:attribute name="start-time" type="xs:int" default="10"/>
				<xs:attribute name="delay" type="xs:int" default="5000"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="FortZone">
		<xs:complexContent>
			<xs:extension base="AbstractZone">
				<xs:sequence>
					<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="fort-id" type="xs:int" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="MotherTreeZone">
		<xs:complexContent>
			<xs:extension base="AbstractZone">
				<xs:attribute name="enter-message" type="xs:int" use="required"/>
				<xs:attribute name="leave-message" type="xs:int" use="required"/>
				<xs:attribute name="regen-mp" type="xs:int" default="1"/>
				<xs:attribute name="regen-hp" type="xs:int" default="1"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="NoLandingZone">
		<xs:complexContent>
			<xs:extension base="AbstractZone">
				<xs:attribute name="dismount-delay" type="xs:int" default="5"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="NoRestartZone">
		<xs:complexContent>
			<xs:extension base="AbstractZone">
				<xs:sequence>
					<xs:element name="attributes" type="NoRestartAttributes"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="NoRestartAttributes">
		<xs:complexContent>
			<xs:extension base="ZoneAttributes">
				<xs:attribute name="allow-time" type="xs:int" default="0"/>
				<xs:attribute name="restart-time" type="xs:int" default="0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="OlympiadStadiumZone">
		<xs:complexContent>
			<xs:extension base="AbstractZone">
				<xs:sequence>
					<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="PeaceZone">
		<xs:complexContent>
			<xs:extension base="AbstractZone">
				<xs:attribute name="allow-store" type="xs:boolean" default="true"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="ResidenceTeleportZone">
		<xs:complexContent>
			<xs:extension base="AbstractZone">
				<xs:sequence>
					<xs:element name="spawn" type="Spawn" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:attribute name="residence-id" type="xs:int" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="SiegeZone">
		<xs:complexContent>
			<xs:extension base="AbstractZone">
				<xs:attribute name="castle-id" type="xs:int" default="0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="SwampZone">
		<xs:complexContent>
			<xs:extension base="Zone">
				<xs:sequence>
					<xs:element name="attributes" type="SwampAttributes" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="SwampAttributes">
		<xs:complexContent>
			<xs:extension base="ZoneAttributes">
				<xs:attribute name="move-bonus" type="xs:float" default="0.5"/>
				<xs:attribute name="castle-id" type="xs:int" default="0"/>
				<xs:attribute name="event-id" type="xs:int" default="0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="TaxZone">
		<xs:complexContent>
			<xs:extension base="AbstractZone">
				<xs:attribute name="castle-id" type="xs:int"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="Zone">
		<xs:complexContent>
			<xs:extension base="AbstractZone">
				<xs:attribute name="type" type="ZoneType"/>
				<xs:attribute name="enter-message" type="xs:int" default="0"/>
				<xs:attribute name="leave-message" type="xs:int" default="0"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="AbstractZone" abstract="true">
		<xs:sequence>
			<xs:element ref="form"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:positiveInteger"/>
		<xs:attribute name="name" type="xs:normalizedString"/>
		<xs:attribute name="enabled" type="xs:boolean" default="true"/>
	</xs:complexType>

	<xs:complexType name="ZoneAttributes">
		<xs:attribute name="enabled" type="xs:boolean" default="true"/>
	</xs:complexType>

	<xs:complexType name="Spawn">
		<xs:complexContent>
			<xs:extension base="Location">
				<xs:attribute name="type" type="SpawnType" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:simpleType name="SpawnType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="banish" />
			<xs:enumeration value="blueBanishPoint" />
			<xs:enumeration value="blueStartPoint" />
			<xs:enumeration value="chaotic" />
			<xs:enumeration value="other" />
			<xs:enumeration value="redBanishPoint" />
			<xs:enumeration value="redStartPoint" />
			<xs:enumeration value="spectatorSpawn" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="Respawn">
		<xs:attribute name="region" type="xs:token" use="required" />
		<xs:attribute name="race" type="Race" use="required" />
	</xs:complexType>

	<xs:complexType name="ZoneForm" abstract="true">
		<xs:attribute name="min-z" type="xs:integer" use="required" />
		<xs:attribute name="max-z" type="xs:integer" use="required" />
	</xs:complexType>

	<xs:complexType name="Cube">
		<xs:complexContent>
			<xs:extension base="ZoneForm">
				<xs:sequence>
					<xs:element name="point" type="Location" minOccurs="2" maxOccurs="2"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="Cylinder">
		<xs:complexContent>
			<xs:extension base="ZoneForm">
				<xs:sequence>
					<xs:element name="point" type="Location"/>
				</xs:sequence>
				<xs:attribute name="radius" type="xs:positiveInteger" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="Polygon">
		<xs:complexContent>
			<xs:extension base="ZoneForm">
				<xs:sequence>
					<xs:element name="point" type="Location" minOccurs="3" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

</xs:schema>

=== L2jOrg/Datapack/data/zones/no-landing.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org zones.xsd">
    <!-- No Landing Zones -->
    <no-landing name="boss_area_antaras">
        <polygon min-z="-4096" max-z="-3896">
            <point x="-58026" y="-190958"/>
            <point x="-98030" y="-190958"/>
            <point x="-97263" y="-35335"/>
            <point x="-5341" y="-34964"/>
            <point x="-5554" y="-4207"/>
            <point x="-129444" y="-4207"/>
        </polygon>

    </no-landing>
    <no-landing name="boss_area_valakas">
        <polygon min-z="-3753" max-z="32767">
            <point x="196710" y="-130845"/>
            <point x="228895" y="-130845"/>
            <point x="229126" y="-96162"/>
            <point x="196478" y="-98187"/>
        </polygon>

    </no-landing>
    <no-landing name="Tower_of_Insolence">
        <polygon min-z="-3349" max-z="32767">
            <point x="102382" y="2297"/>
            <point x="100118" y="30085"/>
            <point x="126188" y="29775"/>
            <point x="127178" y="3979"/>
        </polygon>

    </no-landing>
    <no-landing name="Hell_Bound_Island">
        <polygon min-z="-15000" max-z="15000">
            <point x="-47730" y="228200"/>
            <point x="-33000" y="287833"/>
            <point x="33000" y="287833"/>
            <point x="33000" y="228200"/>
            <point x="-10026" y="228200"/>
        </polygon>

    </no-landing>
    <no-landing name="Rainbow_Spring">
        <polygon min-z="-2610" max-z="15890">
            <point x="147262" y="-130925"/>
            <point x="159640" y="-130952"/>
            <point x="159532" y="-121970"/>
            <point x="147455" y="-121883"/>
        </polygon>

    </no-landing>
    <no-landing name="24_21_nofly">
        <polygon min-z="-716" max-z="15283">
            <point x="131156" y="98394"/>
            <point x="163755" y="98405"/>
            <point x="163747" y="130995"/>
            <point x="131168" y="131006"/>
        </polygon>

    </no-landing>
    <no-landing name="25_21_nofly">
        <polygon min-z="-4044" max-z="11956">
            <point x="163907" y="98398"/>
            <point x="196477" y="98408"/>
            <point x="196495" y="130990"/>
            <point x="164032" y="130993"/>
        </polygon>

    </no-landing>
    <no-landing name="oren01_mb2220_ugoz01_flyno">
        <polygon min-z="-15000" max-z="15000">
            <point x="88417" y="77085"/>
            <point x="105546" y="77041"/>
            <point x="105421" y="92728"/>
            <point x="88481" y="92787"/>
        </polygon>

    </no-landing>

    <!-- High five zone -->
    <no-landing name="olympiad_stadiums">
        <cube min-z="-8485" max-z="1149">
            <point x="-98296" y="-262136"/>
            <point x="-65544" y="-229384"/>
        </cube>

    </no-landing>
</list>

=== L2jOrg/Datapack/data/zones/krateis-cube.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org zones.xsd">
    <!-- Katei's Cube Zones -->
    <peace name="crataer_race1" >
        <polygon min-z="-8355" max-z="-8105">
            <point x="-87901" y="-17029"/>
            <point x="-86611" y="-17044"/>
            <point x="-86618" y="-15767"/>
            <point x="-87894" y="-15770"/>
        </polygon>
</peace>
    <peace name="crataer_race2" >
        <polygon min-z="-8459" max-z="-8209">
            <point x="-87827" y="-82417"/>
            <point x="-86552" y="-82421"/>
            <point x="-86548" y="-81200"/>
            <point x="-87826" y="-81190"/>
        </polygon>
</peace>
    <peace name="crataer_race3" >
        <polygon min-z="-8403" max-z="-8153">
            <point x="-54654" y="-83602"/>
            <point x="-53357" y="-83594"/>
            <point x="-53359" y="-82330"/>
            <point x="-54650" y="-82341"/>
        </polygon>
</peace>
    <zone name="crataer_battle1"  type="PVP" enter-message="283" leave-message="284">
        <polygon min-z="-8375" max-z="-8095">
            <point x="-86726" y="-21076"/>
            <point x="-77193" y="-21079"/>
            <point x="-77321" y="-11710"/>
            <point x="-86670" y="-11714"/>
        </polygon>
    </zone>
    <zone name="crataer_battle2"  type="PVP" enter-message="283" leave-message="284">
        <polygon min-z="-8483" max-z="-8233">
            <point x="-86608" y="-86506"/>
            <point x="-77222" y="-86479"/>
            <point x="-77064" y="-76900"/>
            <point x="-86576" y="-76829"/>
        </polygon>
    </zone>
    <zone name="crataer_battle3"  type="PVP" enter-message="283" leave-message="284">
        <polygon min-z="-8471" max-z="-8221">
            <point x="-53365" y="-87679"/>
            <point x="-43940" y="-87683"/>
            <point x="-43926" y="-78026"/>
            <point x="-53311" y="-77966"/>
        </polygon>
    </zone>
    <no-restart name="cratae_no_restart1" >
        <polygon min-z="-8375" max-z="-8095">
            <point x="-86726" y="-21076"/>
            <point x="-77193" y="-21079"/>
            <point x="-77321" y="-11710"/>
            <point x="-86670" y="-11714"/>
        </polygon>
        <attributes/>
    </no-restart>
    <no-restart name="cratae_no_restart2" >
        <polygon min-z="-8483" max-z="-8233">
            <point x="-86608" y="-86506"/>
            <point x="-77222" y="-86479"/>
            <point x="-77064" y="-76900"/>
            <point x="-86576" y="-76829"/>
        </polygon>
        <attributes/>
    </no-restart>
    <no-restart name="cratae_no_restart3" >
        <polygon min-z="-8471" max-z="-8221">
            <point x="-53365" y="-87679"/>
            <point x="-43940" y="-87683"/>
            <point x="-43926" y="-78026"/>
            <point x="-53311" y="-77966"/>
        </polygon>
        <attributes/>
    </no-restart>
</list>
