=== L2jOrg/Datapack/data/items/items.xsd
<?xml version="1.1" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://l2j.org"
           xmlns="http://l2j.org"
           elementFormDefault="qualified">

    <xs:include schemaLocation="../xsd/common.xsd"/>

    <xs:element name="list">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="itemGroup" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Weapon">
        <xs:complexContent>
            <xs:extension base="AbstractItem">
                <xs:sequence>
                    <xs:element name="attributes" type="WeaponAttributes"/>
                    <xs:element name="random_craft" minOccurs="0" type="RandomCraft"/>
                    <xs:element name="crystal" type="ItemCrystal"/>
                    <xs:element name="damage" type="WeaponDamage" minOccurs="0"/>
                    <xs:element name="stats" minOccurs="0" type="ItemStats"/>
                    <xs:element name="skills" minOccurs="0" type="ItemSkillsType"/>
                </xs:sequence>
                <xs:attribute name="type" type="WeaponType" use="required"/>
                <xs:attribute name="body-part" type="WeaponBodyPart"/>
                <xs:attribute name="magic" type="xs:boolean" default="false"/>
                <xs:attribute name="mana-consume" type="xs:int" default="0"/>
                <xs:attribute name="enchant_bless" type="xs:boolean" default="false"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="WeaponAttributes">
        <xs:complexContent>
            <xs:extension base="Attributes">
                <xs:attribute name="enchant-enabled" type="xs:boolean" default="true"/>
                <xs:attribute name="commission-type" type="CommissionType" default="OTHER_WEAPON"/>
                <xs:attribute name="change-weapon" type="xs:int" default="0"/>
                <xs:attribute name="can-attack" type="xs:boolean" default="true"/>
                <xs:attribute name="restrict-skills" type="xs:boolean" default="false"/>
                <xs:attribute name="hero" type="xs:boolean" default="false"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="WeaponDamage">
        <xs:attribute name="radius" type="xs:int"/>
        <xs:attribute name="angle" type="xs:int"/>
    </xs:complexType>

    <xs:complexType name="Armor">
        <xs:complexContent>
            <xs:extension base="AbstractItem">
                <xs:sequence>
                    <xs:element name="attributes" type="ArmorAttributes"/>
                    <xs:element name="random_craft" minOccurs="0" type="RandomCraft"/>
                    <xs:element name="crystal" type="ItemCrystal"/>
                    <xs:element name="stats" minOccurs="0" type="ItemStats"/>
                    <xs:element name="skills" minOccurs="0" type="ItemSkillsType"/>
                </xs:sequence>
                <xs:attribute name="type" type="ArmorType" use="required"/>
                <xs:attribute name="body-part" type="ArmorBodyPart" use="required"/>
                <xs:attribute name="enchant_bless" type="xs:boolean" default="false"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ArmorAttributes">
        <xs:complexContent>
            <xs:extension base="Attributes">
                <xs:attribute name="enchant-enabled" type="xs:boolean" default="true"/>
                <xs:attribute name="commission-type" type="CommissionType" default="OTHER_ITEM"/>
                <xs:attribute name="hero" type="xs:boolean" default="false"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Item">
        <xs:complexContent>
            <xs:extension base="AbstractItem">
                <xs:sequence>
                    <xs:element name="attributes" type="ItemAttributes"/>
                    <xs:element name="random_craft" minOccurs="0" type="RandomCraft"/>
                    <xs:element name="crystal" type="ItemCrystal" minOccurs="0"/>
                    <xs:choice minOccurs="0">
                        <xs:element name="action" type="ItemAction"/>
                        <xs:element name="extract" type="ItemExtract"/>
                        <xs:element name="skill-reducer" type="SkillReducer"/>
                        <xs:element name="transformation-book" type="TransformationBook"/>
                    </xs:choice>
                </xs:sequence>
                <xs:attribute name="type" type="EtcItemType" use="required"/>
                <xs:attribute name="enchant_bless" type="xs:boolean" default="false"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ItemAttributes">
        <xs:complexContent>
            <xs:extension base="Attributes">
                <xs:attribute name="immediate-effect" type="xs:boolean" default="false"/>
                <xs:attribute name="ex-immediate-effect" type="xs:boolean" default="false"/>
                <xs:attribute name="quest-item" type="xs:boolean" default="false"/>
                <xs:attribute name="self-resurrection" type="xs:boolean" default="false"/>
                <xs:attribute name="infinite" type="xs:boolean" default="false"/>
                <xs:attribute name="commission-type" type="CommissionType" default="OTHER_ITEM"/>
                <xs:attribute name="action" type="ActionType" default="NONE"/>
                <xs:attribute name="auto-use" type="AutoUseType" default="NONE"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="AutoUseType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="NONE"/>
            <xs:enumeration value="SUPPLY"/>
            <xs:enumeration value="HEALING"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="AbstractItem" abstract="true">
        <xs:sequence>
            <xs:element name="restriction" type="Restriction"/>
            <xs:element name="condition" minOccurs="0" type="ItemUseCondition"/>
        </xs:sequence>
        <xs:attribute name="id" use="required" type="xs:positiveInteger"/>
        <xs:attribute name="name" type="xs:normalizedString" use="required"/>
        <xs:attribute name="display-id" type="xs:int"/>
    </xs:complexType>

    <xs:complexType name="Restriction">
        <xs:attribute name="stackable" type="xs:boolean" default="false"/>
        <xs:attribute name="sellable" type="xs:boolean" default="true"/>
        <xs:attribute name="private-sellable" type="xs:boolean" default="true"/>
        <xs:attribute name="dropable" type="xs:boolean" default="true"/>
        <xs:attribute name="destroyable" type="xs:boolean" default="true"/>
        <xs:attribute name="tradable" type="xs:boolean" default="true"/>
        <xs:attribute name="depositable" type="xs:boolean" default="true"/>
        <xs:attribute name="clan-depositable" type="xs:boolean" default="true"/>
        <xs:attribute name="castle-depositable" type="xs:boolean" default="true"/>
        <xs:attribute name="freightable" type="xs:boolean" default="true"/>
        <xs:attribute name="commissionable" type="xs:boolean" default="true"/>
        <xs:attribute name="mailable" type="xs:boolean" default="true"/>
        <xs:attribute name="olympiad-restricted" type="xs:boolean" default="false"/>
        <xs:attribute name="hero" type="xs:boolean" default="false"/>
    </xs:complexType>

    <xs:complexType name="Attributes" abstract="true">
        <xs:attribute name="weight" type="xs:int" default="0"/>
        <xs:attribute name="price" type="xs:long" default="0"/>
        <xs:attribute name="duration" type="xs:long" default="-1"/>
        <xs:attribute name="reuse-delay" type="xs:long" />
        <xs:attribute name="for-npc" type="xs:boolean" default="false"/>
    </xs:complexType>

    <xs:complexType name="RandomCraft">
        <xs:attribute name="craft" type="xs:long" default="0"/>
        <xs:attribute name="enchant" type="xs:byte" default="0"/>
        <xs:attribute name="exp" type="xs:long" default="0"/>
        <xs:attribute name="commission" type="xs:long" default="0"/>
        <xs:attribute name="locked" type="xs:boolean" default="false"/>
    </xs:complexType>

    <xs:complexType name="ItemCrystal">
        <xs:attribute name="type" type="CrystalType" default="NONE"/>
        <xs:attribute name="count" type="xs:int" default="0"/>
    </xs:complexType>

    <xs:complexType name="TransformationBook">
        <xs:attribute name="skill" type="xs:int" use="required"/>
    </xs:complexType>

    <xs:complexType name="SkillReducer">
        <xs:sequence>
            <xs:element name="skill" type="ItemSkillType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="type" type="xs:token" default="ItemSkills"/>
    </xs:complexType>

    <xs:complexType name="ItemExtract">
        <xs:sequence>
            <xs:element name="item" type="ExtractableItem" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="max" type="xs:int" default="-1"/>
    </xs:complexType>

    <xs:complexType name="ItemAction">
        <xs:attribute name="handler">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="BeastSoulShot"/>
                    <xs:enumeration value="BeastSpiritShot"/>
                    <xs:enumeration value="BlessedSoulShots"/>
                    <xs:enumeration value="BlessedSpiritShot"/>
                    <xs:enumeration value="Book"/>
                    <xs:enumeration value="Bypass"/>
                    <xs:enumeration value="Calculator"/>
                    <xs:enumeration value="ChangeAttributeCrystal"/>
                    <xs:enumeration value="CharmOfCourage"/>
                    <xs:enumeration value="EnchantScrolls"/>
                    <xs:enumeration value="EventItem"/>
                    <xs:enumeration value="FatedSupportBox"/>
                    <xs:enumeration value="FishShots"/>
                    <xs:enumeration value="Harvester"/>
                    <xs:enumeration value="Maps"/>
                    <xs:enumeration value="MercTicket"/>
                    <xs:enumeration value="NicknameColor"/>
                    <xs:enumeration value="PetFood"/>
                    <xs:enumeration value="Recipes"/>
                    <xs:enumeration value="RollingDice"/>
                    <xs:enumeration value="Seed"/>
                    <xs:enumeration value="SoulShots"/>
                    <xs:enumeration value="SpecialXMas"/>
                    <xs:enumeration value="SpiritShot"/>
                    <xs:enumeration value="SummonItems"/>
                    <xs:enumeration value="BlessedScroll"/>
                    <xs:enumeration value="TransformationBook"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="ItemSkillsType">
        <xs:sequence>
            <xs:element name="skill" type="ItemSkillType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ItemSkillType">
        <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
        <xs:attribute name="level" type="xs:positiveInteger" default="1"/>
        <xs:attribute name="type" default="NORMAL">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="NORMAL"/>
                    <xs:enumeration value="ON_ENCHANT"/>
                    <xs:enumeration value="ON_EQUIP"/>
                    <xs:enumeration value="ON_UNEQUIP"/>
                    <xs:enumeration value="ON_CRITICAL_SKILL"/>
                    <xs:enumeration value="ON_MAGIC_SKILL"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="chance" type="xs:positiveInteger" default="100"/>
        <xs:attribute name="value" type="xs:int" default="0"/>
    </xs:complexType>

    <xs:complexType name="ExtractableItem">
        <xs:attribute name="id" type="xs:positiveInteger"/>
        <xs:attribute name="min-count" type="xs:positiveInteger" default="1"/>
        <xs:attribute name="max-count" type="xs:positiveInteger" default="1"/>
        <xs:attribute name="chance" type="xs:positiveInteger" default="100"/>
        <xs:attribute name="min-enchant" type="xs:nonNegativeInteger" default="0"/>
        <xs:attribute name="max-enchant" type="xs:nonNegativeInteger" default="0"/>
    </xs:complexType>

    <xs:complexType name="createItemType">
        <xs:attribute name="id" type="xs:positiveInteger"/>
        <xs:attribute name="count" type="xs:positiveInteger"/>
        <xs:attribute name="chance" type="xs:double"/>
    </xs:complexType>

    <xs:complexType name="playerType">
        <xs:attribute name="castle">
            <xs:simpleType>
                <xs:restriction base="xs:int">
                    <xs:minInclusive value="-1"/>
                    <xs:maxInclusive value="9"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="hero" type="xs:boolean"/>
        <xs:attribute name="zone" type="xs:normalizedString"/>
        <xs:attribute name="level-min" type="xs:positiveInteger"/>
        <xs:attribute name="social-status" type="SocialStatus"/>
        <xs:attribute name="level-max" type="xs:positiveInteger"/>
        <xs:attribute name="sex">
            <xs:simpleType>
                <xs:restriction base="xs:token">
                    <xs:enumeration value="FEMALE"/>
                    <xs:enumeration value="MALE"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="chaotic" type="xs:boolean"/>
        <xs:attribute name="flying" type="xs:boolean"/>
        <xs:attribute name="races" type="RaceList"/>
    </xs:complexType>

    <xs:complexType name="ItemUseCondition">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="player" type="playerType"/>
        </xs:choice>
        <xs:attribute name="msg-id" type="xs:short" />
        <xs:attribute name="add-name" type="xs:boolean" />
        <xs:attribute name="msg" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="ItemStats">
        <xs:sequence>
            <xs:element name="stat" type="ItemStat" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ItemStat">
        <xs:attribute name="type" type="Stat"/>
        <xs:attribute name="value" type="xs:float"/>
    </xs:complexType>

    <xs:simpleType name="CommissionType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="ONE_HAND_SWORD"/>
            <xs:enumeration value="ONE_HAND_MAGIC_SWORD"/>
            <xs:enumeration value="DAGGER"/>
            <xs:enumeration value="RAPIER"/>
            <xs:enumeration value="TWO_HAND_SWORD"/>
            <xs:enumeration value="ANCIENT_SWORD"/>
            <xs:enumeration value="DUALSWORD"/>
            <xs:enumeration value="DUAL_DAGGER"/>
            <xs:enumeration value="BLUNT_WEAPON"/>
            <xs:enumeration value="ONE_HAND_MAGIC_BLUNT_WEAPON"/>
            <xs:enumeration value="TWO_HAND_BLUNT_WEAPON"/>
            <xs:enumeration value="TWO_HAND_MAGIC_BLUNT_WEAPON"/>
            <xs:enumeration value="DUAL_BLUNT_WEAPON"/>
            <xs:enumeration value="BOW"/>
            <xs:enumeration value="CROSSBOW"/>
            <xs:enumeration value="FIST_WEAPON"/>
            <xs:enumeration value="SPEAR"/>
            <xs:enumeration value="OTHER_WEAPON"/>
            <xs:enumeration value="HELMET"/>
            <xs:enumeration value="ARMOR_TOP"/>
            <xs:enumeration value="ARMOR_PANTS"/>
            <xs:enumeration value="FULL_BODY"/>
            <xs:enumeration value="GLOVES"/>
            <xs:enumeration value="FEET"/>
            <xs:enumeration value="SHIELD"/>
            <xs:enumeration value="SIGIL"/>
            <xs:enumeration value="UNDERWEAR"/>
            <xs:enumeration value="CLOAK"/>
            <xs:enumeration value="RING"/>
            <xs:enumeration value="EARRING"/>
            <xs:enumeration value="NECKLACE"/>
            <xs:enumeration value="BELT"/>
            <xs:enumeration value="BRACELET"/>
            <xs:enumeration value="HAIR_ACCESSORY"/>
            <xs:enumeration value="POTION"/>
            <xs:enumeration value="SCROLL_ENCHANT_WEAPON"/>
            <xs:enumeration value="SCROLL_ENCHANT_ARMOR"/>
            <xs:enumeration value="SCROLL_OTHER"/>
            <xs:enumeration value="SOULSHOT"/>
            <xs:enumeration value="SPIRITSHOT"/>
            <xs:enumeration value="PET_EQUIPMENT"/>
            <xs:enumeration value="PET_SUPPLIES"/>
            <xs:enumeration value="CRYSTAL"/>
            <xs:enumeration value="RECIPE"/>
            <xs:enumeration value="MAJOR_CRAFTING_INGREDIENTS"/>
            <xs:enumeration value="LIFE_STONE"/>
            <xs:enumeration value="SOUL_CRYSTAL"/>
            <xs:enumeration value="ATTRIBUTE_STONE"/>
            <xs:enumeration value="WEAPON_ENCHANT_STONE"/>
            <xs:enumeration value="ARMOR_ENCHANT_STONE"/>
            <xs:enumeration value="SPELLBOOK"/>
            <xs:enumeration value="GEMSTONE"/>
            <xs:enumeration value="POUCH"/>
            <xs:enumeration value="PIN"/>
            <xs:enumeration value="MAGIC_RUNE_CLIP"/>
            <xs:enumeration value="MAGIC_ORNAMENT"/>
            <xs:enumeration value="DYES"/>
            <xs:enumeration value="OTHER_ITEM"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="itemGroup" type="AbstractItem" abstract="true" />
    <xs:element name="weapon" type="Weapon" substitutionGroup="itemGroup"/>
    <xs:element name="armor" type="Armor" substitutionGroup="itemGroup"/>
    <xs:element name="item" type="Item" substitutionGroup="itemGroup"/>

    <xs:simpleType name="ActionType">
        <xs:restriction base="xs:token">
            <xs:enumeration value="CALC"/>
            <xs:enumeration value="CALL_SKILL"/>
            <xs:enumeration value="CAPSULE"/>
            <xs:enumeration value="CREATE_MPCC"/>
            <xs:enumeration value="DICE"/>
            <xs:enumeration value="EQUIP"/>
            <xs:enumeration value="FISHINGSHOT"/>
            <xs:enumeration value="HARVEST"/>
            <xs:enumeration value="HIDE_NAME"/>
            <xs:enumeration value="KEEP_EXP"/>
            <xs:enumeration value="NICK_COLOR"/>
            <xs:enumeration value="NONE"/>
            <xs:enumeration value="PEEL"/>
            <xs:enumeration value="RECIPE"/>
            <xs:enumeration value="SEED"/>
            <xs:enumeration value="SHOW_ADVENTURER_GUIDE_BOOK"/>
            <xs:enumeration value="SHOW_HTML"/>
            <xs:enumeration value="SHOW_SSQ_STATUS"/>
            <xs:enumeration value="SKILL_MAINTAIN"/>
            <xs:enumeration value="SKILL_REDUCE"/>
            <xs:enumeration value="SOULSHOT"/>
            <xs:enumeration value="SPIRITSHOT"/>
            <xs:enumeration value="START_QUEST"/>
            <xs:enumeration value="SUMMON_SOULSHOT"/>
            <xs:enumeration value="SUMMON_SPIRITSHOT"/>
            <xs:enumeration value="XMAS_OPEN"/>
            <xs:enumeration value="SKILL_REDUCE_ON_SKILL_SUCCESS"/>
            <xs:enumeration value="SHOW_TUTORIAL"/>
        </xs:restriction>

    </xs:simpleType>
</xs:schema>

=== L2jOrg/Datapack/data/items/38200-38299.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org items.xsd">
	<weapon id="38211" name="Blue Mackerel: One-handed Sword" type="SWORD" body-part="RIGHT_HAND">
		<restriction freightable="false" dropable="false" sellable="false"/>
		<attributes weight="1450" commission-type="OTHER_ITEM" enchant-enabled="false"/>
		<crystal />
		<damage radius="40" angle="240"/>
		<stats>
			<stat type="CRITICAL_RATE" value="8.0"/>
			<stat type="MAGIC_ATTACK" value="47.0"/>
			<stat type="PHYSICAL_ATTACK" value="79.0"/>
			<stat type="PHYSICAL_ATTACK_RANGE" value="40.0"/>
			<stat type="PHYSICAL_ATTACK_SPEED" value="379.0"/>
			<stat type="RANDOM_DAMAGE" value="10.0"/>
		</stats>
	</weapon>

	<weapon id="38212" name="Trumpetfish: Dagger" type="DAGGER" body-part="RIGHT_HAND">
		<restriction freightable="false" dropable="false" sellable="false"/>
		<attributes weight="1070" commission-type="OTHER_ITEM" enchant-enabled="false"/>
		<crystal />
		<damage radius="40" angle="240"/>
		<stats>
			<stat type="ACCURACY" value="-3.75"/>
			<stat type="CRITICAL_RATE" value="12.0"/>
			<stat type="MAGIC_ATTACK" value="42.0"/>
			<stat type="PHYSICAL_ATTACK" value="62.0"/>
			<stat type="PHYSICAL_ATTACK_RANGE" value="40.0"/>
			<stat type="PHYSICAL_ATTACK_SPEED" value="433.0"/>
			<stat type="RANDOM_DAMAGE" value="5.0"/>
		</stats>
	</weapon>

	<weapon id="38213" name="Shark: Two-handed Sword" type="TWO_HAND_SWORD" body-part="TWO_HAND">
		<restriction freightable="false" dropable="false" sellable="false"/>
		<attributes weight="2020" commission-type="OTHER_ITEM" enchant-enabled="false"/>
		<crystal />
		<damage radius="40" angle="240"/>
		<stats>
			<stat type="CRITICAL_RATE" value="8.0"/>
			<stat type="MAGIC_ATTACK" value="47.0"/>
			<stat type="PHYSICAL_ATTACK" value="96.0"/>
			<stat type="PHYSICAL_ATTACK_RANGE" value="40.0"/>
			<stat type="PHYSICAL_ATTACK_SPEED" value="325.0"/>
			<stat type="RANDOM_DAMAGE" value="10.0"/>
		</stats>
	</weapon>

	<weapon id="38214" name="Squid: Spear" type="SPEAR" body-part="TWO_HAND">
		<restriction freightable="false" dropable="false" sellable="false"/>
		<attributes weight="2060" commission-type="OTHER_ITEM" enchant-enabled="false"/>
		<crystal />
		<damage radius="66" angle="240"/>
		<stats>
			<stat type="ACCURACY" value="-3.75"/>
			<stat type="CRITICAL_RATE" value="8.0"/>
			<stat type="MAGIC_ATTACK" value="47.0"/>
			<stat type="PHYSICAL_ATTACK" value="79.0"/>
			<stat type="PHYSICAL_ATTACK_RANGE" value="80.0"/>
			<stat type="PHYSICAL_ATTACK_SPEED" value="325.0"/>
			<stat type="RANDOM_DAMAGE" value="10.0"/>
		</stats>
		<skills>
			<skill id="3599" value="-1"/>  <!-- Polearm Multi-attack -->
		</skills>
	</weapon>

	<weapon id="38215" name="Sea Horse: Two-handed Magic Blunt Weapon" type="STAFF" body-part="TWO_HAND" magic="true">
		<restriction freightable="false" dropable="false" sellable="false"/>
		<attributes weight="1000" commission-type="OTHER_ITEM" enchant-enabled="false"/>
		<crystal />
		<damage radius="40" angle="240"/>
		<stats>
			<stat type="ACCURACY" value="8.0"/>
			<stat type="CRITICAL_RATE" value="6.0"/>
			<stat type="MAGIC_ATTACK" value="69.0"/>
			<stat type="PHYSICAL_ATTACK" value="77.0"/>
			<stat type="PHYSICAL_ATTACK_RANGE" value="40.0"/>
			<stat type="PHYSICAL_ATTACK_SPEED" value="325.0"/>
			<stat type="RANDOM_DAMAGE" value="19.0"/>
		</stats>
	</weapon>

	<weapon id="38216" name="Lobster: Fist Weapon" type="FIST" body-part="TWO_HAND">
		<restriction freightable="false" dropable="false" sellable="false"/>
		<attributes weight="1510" commission-type="OTHER_ITEM" enchant-enabled="false"/>
		<crystal />
		<damage radius="40" angle="240"/>
		<stats>
			<stat type="ACCURACY" value="8.0"/>
			<stat type="CRITICAL_RATE" value="6.0"/>
			<stat type="MAGIC_ATTACK" value="47.0"/>
			<stat type="PHYSICAL_ATTACK" value="96.0"/>
			<stat type="PHYSICAL_ATTACK_RANGE" value="40.0"/>
			<stat type="PHYSICAL_ATTACK_SPEED" value="325.0"/>
			<stat type="RANDOM_DAMAGE" value="5.0"/>
		</stats>
	</weapon>

	<weapon id="38217" name="Giant Crab: Bow" type="BOW" body-part="TWO_HAND" mana-consume="2">
		<restriction freightable="false" dropable="false" sellable="false"/>
		<attributes weight="1820" commission-type="OTHER_ITEM" reuse-delay="1500" enchant-enabled="false"/>
		<crystal />
		<damage radius="40" angle="240"/>
		<stats>
			<stat type="ACCURACY" value="-3.75"/>
			<stat type="CRITICAL_RATE" value="12.0"/>
			<stat type="MAGIC_ATTACK" value="51.0"/>
			<stat type="PHYSICAL_ATTACK" value="179.0"/>
			<stat type="PHYSICAL_ATTACK_RANGE" value="500.0"/>
			<stat type="PHYSICAL_ATTACK_SPEED" value="293.0"/>
			<stat type="RANDOM_DAMAGE" value="5.0"/>
		</stats>
	</weapon>

	<armor id="38220" name="Turtle: Shield" type="SHIELD" body-part="LEFT_HAND">
		<restriction freightable="false" dropable="false" sellable="false"/>
		<attributes weight="1320" enchant-enabled="false" />
		<crystal />
		<stats>
			<stat type="SHIELD_DEFENCE" value="142.0"/>
			<stat type="SHIELD_DEFENCE_RATE" value="20.0"/>
		</stats>
	</armor>

	<weapon id="38221" name="Blue Mackerel: Dual Sword" type="DUAL" body-part="TWO_HAND">
		<restriction freightable="false" dropable="false" sellable="false"/>
		<attributes weight="2530" commission-type="OTHER_ITEM"/>
		<crystal />
		<damage radius="40" angle="240"/>
		<stats>
			<stat type="CRITICAL_RATE" value="8.0"/>
			<stat type="MAGIC_ATTACK" value="47.0"/>
			<stat type="PHYSICAL_ATTACK" value="96.0"/>
			<stat type="PHYSICAL_ATTACK_RANGE" value="40.0"/>
			<stat type="PHYSICAL_ATTACK_SPEED" value="325.0"/>
			<stat type="RANDOM_DAMAGE" value="10.0"/>
		</stats>
	</weapon>

</list>

=== L2jOrg/Datapack/data/items/72100-72199.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org items.xsd">
	<item id="72100" name="Devoted Hero's Doll - Baium" type="NONE">
	<!-- <Baium Doll's Sorcery Lv. 3>\nSkill Cooldown -4%\nP. Def. +15%\nM. Def. +15%\nSilence Resistance +45%\nFear Resistance +45%\nParalysis Resistance +25%\nKnockback Resistance +25%\nPull Resistance +25%\n\nBoosts parameters when in inventory. -->
		<restriction stackable="true" tradable="false" dropable="false" sellable="false" private-sellable="false" clan-depositable="false" castle-depositable="false" freightable="false"/>
		<attributes/>
	</item>

	<item id="72101" name="Devoted Hero's Doll - Orfen" type="NONE">
	<!-- <Orfen Doll's Sorcery Lv. 3>\nM. Atk. +15%\nM. Skill Critical Damage +10%\nMax MP +15%\n\nBoosts parameters when in inventory. -->
		<restriction stackable="true" tradable="false" dropable="false" sellable="false" private-sellable="false" clan-depositable="false" castle-depositable="false" freightable="false"/>
		<attributes/>
	</item>

	<item id="72102" name="Devoted Hero's Doll - Frintezza" type="NONE">
	<!-- <Frintezza Doll's Sorcery Lv. 3>\nSTR/ INT +2\nDEX/ WIT +2\nCON/ MEN +2\nSkill Power +5%\nAtk. Spd. +100\nCasting Spd. +100\nSpeed +5\n\nBoosts parameters when in inventory. -->
		<restriction stackable="true" tradable="false" dropable="false" sellable="false" private-sellable="false" clan-depositable="false" castle-depositable="false" freightable="false"/>
		<attributes/>
	</item>

	<item id="72111" name="New Year Gift" type="SCROLL">
	<!-- Applies a buff when used.\n\n<Buff effect>\nAtk. Spd./ Casting Spd. +5%\nHP/ MP Recovery Rate +5%\nSpeed +10\n\nDuration: 30 min.\nChanges the armor appearance to that of Santa Outfit. -->
		<restriction tradable="false" dropable="false" sellable="false" private-sellable="false" clan-depositable="false" castle-depositable="false" freightable="false"/>
		<attributes/>
	</item>

	<item id="72114" name="Christmas Kit" type="NONE">
	<!-- Double-click to obtain the following items. -->
		<restriction tradable="false" dropable="false" sellable="false" private-sellable="false" clan-depositable="false" castle-depositable="false" freightable="false"/>
		<attributes/>
	</item>

	<item id="72115" name="Match Girls' Gift" type="NONE">
	<!-- A gift from the Match Girls who are thankful for your help. Double-click to obtain one of the following items. -->
		<restriction tradable="false" dropable="false" sellable="false" private-sellable="false" clan-depositable="false" castle-depositable="false" freightable="false"/>
		<attributes/>
	</item>

	<item id="72179" name="Top-grade Grade A Weapon Pack" type="NONE">
	<!-- Double-click to obtain one of the following items. -->
		<restriction tradable="false" dropable="false" sellable="false" private-sellable="false" clan-depositable="false" castle-depositable="false" freightable="false"/>
		<attributes/>
	</item>

	<item id="72186" name="Special Kit" type="NONE">
	<!-- Double-click to obtain one of the specified items.\n<font color=eeaa22>The right to the priority logging-in is granted until the last day of the month in which the item has been used.</font> -->
		<restriction tradable="false" dropable="false" sellable="false" private-sellable="false" clan-depositable="false" castle-depositable="false" freightable="false"/>
		<attributes/>
	</item>

	<item id="72190" name="Lucky Kit" type="NONE">
	<!-- Double-click to obtain the following items. -->
		<restriction tradable="false" dropable="false" sellable="false" private-sellable="false" clan-depositable="false" castle-depositable="false" freightable="false"/>
		<attributes/>
	</item>

	<item id="72191" name="L-Coins (1000 pcs.)" type="NONE">
	<!-- Double-click to obtain the following items. -->
		<restriction tradable="false" dropable="false" sellable="false" private-sellable="false" clan-depositable="false" castle-depositable="false" freightable="false"/>
		<attributes/>
	</item>

	<item id="72192" name="L-Coins (8000 pcs.)" type="NONE">
	<!-- Double-click to obtain the following items. -->
		<restriction tradable="false" dropable="false" sellable="false" private-sellable="false" clan-depositable="false" castle-depositable="false" freightable="false"/>
		<attributes/>
	</item>

</list>
