=== L2jOrg/Datapack/data/residences/clanHalls/clanHall.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   targetNamespace="https://l2j.org"
		   xmlns="https://l2j.org"
		   elementFormDefault="qualified">

	<xs:include schemaLocation="../../xsd/common.xsd"/>

	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="clanHall" type="ClanHall" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="ClanHall">
		<xs:sequence>
			<xs:element name="auction" type="Auction"/>
			<xs:element name="npcs"  type="intList"/>
			<xs:element name="doors" type="intList"/>
			<xs:element name="restart-point" type="Location"/>
			<xs:element name="banish-point" type="Location"/>
		</xs:sequence>
		<xs:attribute type="xs:short" name="id" use="required" />
		<xs:attribute type="xs:string" name="name" />
		<xs:attribute name="grade" type="CrystalType" default="NONE"/>
		<xs:attribute name="type" type="ClanHallType" default="OTHER"/>
	</xs:complexType>

	<xs:complexType name="Auction">
		<xs:attribute name="min-bid" type="xs:long" use="required" />
		<xs:attribute name="lease" type="xs:long" use="required" />
	</xs:complexType>

	<xs:simpleType name="ClanHallType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="AUCTIONABLE" />
			<xs:enumeration value="SIEGEABLE" />
			<xs:enumeration value="INSTANCED" />
			<xs:enumeration value="OTHER" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== L2jOrg/Datapack/data/residences/clanHalls/floran.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xmlns="http://l2j.org" xsi:schemaLocation="http://l2j.org clanHall.xsd" >
    <clanHall id="73" name="Black Barracks" grade="B" type="AUCTIONABLE">
        <auction min-bid="5000000" lease="500000"/>
        <npcs>
            36738 <!-- Ludina -->
            36737 <!-- Gairin -->
        </npcs>
        <doors>
            20230101
            20230102
        </doors>
        <restart-point x="17194" y="169658" z="-3486" />
        <banish-point x="18318" y="170344" z="-3501" />
    </clanHall>

    <clanHall id="74" name="Green Barracks" grade="B" type="AUCTIONABLE">
        <auction min-bid="5000000" lease="500000"/>
        <npcs>
            36740 <!-- Danif -->
            36739 <!-- Flon -->
        </npcs>
        <doors>
            20230103
            20230104
        </doors>
        <restart-point x="17965" y="170734" z="-3491" />
        <banish-point x="18318" y="170344" z="-3501" />
    </clanHall>
</list>
